export interface DataSourceConfig {
  key: string;
  backend?: 'd1' | 'supabase' | 'mixed';
  endpoint: string;
  refreshSeconds: number;
  defaultRange: '24h' | '7d' | '30d' | 'all';
  supportedChartTypes: string[];
  primaryTable: string;
  fallbackTable?: string;
  status:
    | 'active'
    | 'not_connected_yet'
    | 'active_but_low_volume'
    | 'config_only'
    | 'empty_capability'
    | 'legacy_ignore'
    | 'unknown';
}

export const ANALYTICS_DATA_SOURCES: Record<string, DataSourceConfig> = {
  systemPulse: {
    key: 'systemPulse',
    backend: 'mixed',
    endpoint: '/api/analytics/overview',
    refreshSeconds: 60,
    defaultRange: '7d',
    supportedChartTypes: ['metric_card', 'sparkline', 'time_series'],
    primaryTable: 'agentsam_usage_events',
    status: 'active',
  },
  workflowRuns: {
    key: 'workflowRuns',
    backend: 'd1',
    endpoint: '/api/analytics/agent/runs',
    refreshSeconds: 60,
    defaultRange: '7d',
    supportedChartTypes: ['metric_card', 'time_series', 'stacked_bar', 'table', 'drawer'],
    primaryTable: 'agentsam_workflow_runs',
    status: 'active',
  },
  workflowGraph: {
    key: 'workflowGraph',
    backend: 'd1',
    endpoint: '/api/analytics/agent/graph',
    refreshSeconds: 120,
    defaultRange: '7d',
    supportedChartTypes: ['dag', 'waterfall', 'drawer'],
    primaryTable: 'agentsam_workflow_nodes',
    fallbackTable: 'agentsam_workflow_edges',
    status: 'active',
  },
  dependencyGraph: {
    key: 'dependencyGraph',
    backend: 'd1',
    endpoint: '/api/analytics/agent/dependencies',
    refreshSeconds: 120,
    defaultRange: '7d',
    supportedChartTypes: ['dag', 'table', 'drawer'],
    primaryTable: 'agentsam_execution_dependency_graph',
    status: 'not_connected_yet',
  },
  toolCalls: {
    key: 'toolCalls',
    backend: 'mixed',
    endpoint: '/api/analytics/mcp/tools',
    refreshSeconds: 30,
    defaultRange: '24h',
    supportedChartTypes: ['waterfall', 'leaderboard', 'table', 'stacked_bar'],
    primaryTable: 'agentsam_mcp_tool_execution',
    fallbackTable: 'agentsam_tool_call_log',
    status: 'active',
  },
  modelLeaderboard: {
    key: 'modelLeaderboard',
    backend: 'mixed',
    endpoint: '/api/analytics/models/leaderboard',
    refreshSeconds: 120,
    defaultRange: '7d',
    supportedChartTypes: ['leaderboard_table', 'scatter', 'bar'],
    primaryTable: 'agentsam_execution_performance_metrics',
    status: 'active',
  },
  routingArms: {
    key: 'routingArms',
    backend: 'd1',
    endpoint: '/api/analytics/models/routing-arms',
    refreshSeconds: 300,
    defaultRange: '30d',
    supportedChartTypes: ['table', 'bar', 'status_grid'],
    primaryTable: 'agentsam_routing_arms',
    fallbackTable: 'agentsam_model_routing_memory',
    status: 'not_connected_yet',
  },
  costTrend: {
    key: 'costTrend',
    backend: 'mixed',
    endpoint: '/api/analytics/costs',
    refreshSeconds: 300,
    defaultRange: '30d',
    supportedChartTypes: ['time_series', 'donut', 'table', 'metric_card'],
    primaryTable: 'agentsam_usage_events',
    fallbackTable: 'agentsam_usage_rollups_daily',
    status: 'active',
  },
  dataHealth: {
    key: 'dataHealth',
    backend: 'd1',
    endpoint: '/api/analytics/data-health',
    refreshSeconds: 300,
    defaultRange: '24h',
    supportedChartTypes: ['table', 'status_grid', 'warning_strip'],
    primaryTable: 'agentsam_cron_runs',
    fallbackTable: 'agentsam_compaction_events',
    status: 'active',
  },
  r2Inventory: {
    key: 'r2Inventory',
    backend: 'd1',
    endpoint: '/api/analytics/workers/r2',
    refreshSeconds: 600,
    defaultRange: 'all',
    supportedChartTypes: ['metric_card', 'table', 'donut'],
    primaryTable: 'r2_object_inventory',
    fallbackTable: 'r2_bucket_summary',
    status: 'active',
  },
};

export const SUPABASE_ANALYTICS_DATA_SOURCES: Record<string, DataSourceConfig> = {
  supabaseRagDocuments: {
    key: 'supabaseRagDocuments',
    backend: 'supabase',
    endpoint: '/api/analytics/rag/documents',
    refreshSeconds: 600,
    defaultRange: 'all',
    supportedChartTypes: ['metric_card', 'donut', 'table', 'gauge'],
    primaryTable: 'documents',
    status: 'active',
  },
  supabaseSemanticSearch: {
    key: 'supabaseSemanticSearch',
    backend: 'supabase',
    endpoint: '/api/analytics/rag/search-log',
    refreshSeconds: 600,
    defaultRange: '30d',
    supportedChartTypes: ['metric_card', 'time_series', 'table'],
    primaryTable: 'semantic_search_log',
    status: 'active_but_low_volume',
  },
  supabaseCodebase: {
    key: 'supabaseCodebase',
    backend: 'supabase',
    endpoint: '/api/analytics/codebase/overview',
    refreshSeconds: 600,
    defaultRange: 'all',
    supportedChartTypes: ['metric_card', 'donut', 'treemap', 'table'],
    primaryTable: 'codebase_files',
    fallbackTable: 'codebase_snapshots',
    status: 'active',
  },
  supabaseCodeSymbols: {
    key: 'supabaseCodeSymbols',
    backend: 'supabase',
    endpoint: '/api/analytics/codebase/symbols',
    refreshSeconds: 600,
    defaultRange: 'all',
    supportedChartTypes: ['table', 'bar', 'route_map'],
    primaryTable: 'codebase_symbols',
    status: 'active',
  },
  supabaseCodeChunks: {
    key: 'supabaseCodeChunks',
    backend: 'supabase',
    endpoint: '/api/analytics/codebase/chunks',
    refreshSeconds: 600,
    defaultRange: 'all',
    supportedChartTypes: ['metric_card', 'table'],
    primaryTable: 'codebase_chunks',
    status: 'active',
  },
  supabaseEvalRuns: {
    key: 'supabaseEvalRuns',
    backend: 'supabase',
    endpoint: '/api/analytics/models/evals',
    refreshSeconds: 300,
    defaultRange: '30d',
    supportedChartTypes: ['metric_card', 'table', 'time_series'],
    primaryTable: 'agentsam_eval_runs',
    status: 'active',
  },
  supabaseToolCallEvents: {
    key: 'supabaseToolCallEvents',
    backend: 'supabase',
    endpoint: '/api/analytics/tools/events',
    refreshSeconds: 300,
    defaultRange: '7d',
    supportedChartTypes: ['leaderboard', 'table', 'waterfall'],
    primaryTable: 'agentsam_tool_call_events',
    status: 'active',
  },
  supabaseErrorEvents: {
    key: 'supabaseErrorEvents',
    backend: 'supabase',
    endpoint: '/api/analytics/errors/events',
    refreshSeconds: 300,
    defaultRange: '7d',
    supportedChartTypes: ['table', 'stacked_bar', 'drawer'],
    primaryTable: 'agentsam_error_events',
    status: 'active',
  },
  supabaseRoutingDecisions: {
    key: 'supabaseRoutingDecisions',
    backend: 'supabase',
    endpoint: '/api/analytics/models/routing-decisions',
    refreshSeconds: 600,
    defaultRange: '30d',
    supportedChartTypes: ['table', 'sankey_like', 'metric_card'],
    primaryTable: 'agentsam_routing_decisions',
    status: 'active',
  },
  supabaseStreamEvents: {
    key: 'supabaseStreamEvents',
    backend: 'supabase',
    endpoint: '/api/analytics/agent/stream-events',
    refreshSeconds: 300,
    defaultRange: '30d',
    supportedChartTypes: ['metric_card', 'time_series', 'table'],
    primaryTable: 'agentsam_stream_events',
    status: 'active',
  },
  supabaseBuildDeployEvents: {
    key: 'supabaseBuildDeployEvents',
    backend: 'supabase',
    endpoint: '/api/analytics/deploys/build-events',
    refreshSeconds: 600,
    defaultRange: '30d',
    supportedChartTypes: ['timeline', 'table', 'metric_card'],
    primaryTable: 'build_deploy_events',
    status: 'active',
  },
  supabaseCostForecasts: {
    key: 'supabaseCostForecasts',
    backend: 'supabase',
    endpoint: '/api/analytics/costs/forecasts',
    refreshSeconds: 600,
    defaultRange: '30d',
    supportedChartTypes: ['metric_card', 'time_series', 'table'],
    primaryTable: 'cost_forecasts',
    status: 'active',
  },
  supabasePromptRuns: {
    key: 'supabasePromptRuns',
    backend: 'supabase',
    endpoint: '/api/analytics/prompts/runs',
    refreshSeconds: 600,
    defaultRange: '30d',
    supportedChartTypes: ['empty_state', 'table'],
    primaryTable: 'agentsam_prompt_runs',
    status: 'empty_capability',
  },
  supabaseModelPerformanceSnapshots: {
    key: 'supabaseModelPerformanceSnapshots',
    backend: 'supabase',
    endpoint: '/api/analytics/models/performance-snapshots',
    refreshSeconds: 600,
    defaultRange: '30d',
    supportedChartTypes: ['empty_state', 'leaderboard', 'table'],
    primaryTable: 'model_performance_snapshots',
    status: 'empty_capability',
  },
};

