-- Verified browser capability tools.
-- These tool_names exist in src/tools/builtin/web.js and/or src/tools/ai-dispatch.js.
-- No transactions. No temp tables. No destructive changes.

INSERT INTO agentsam_tools (
  tool_name,
  display_name,
  tool_category,
  handler_type,
  description,
  input_schema,
  output_schema,
  handler_config,
  intent_tags,
  intent_category_tags,
  modes_json,
  risk_level,
  requires_approval,
  requires_confirmation,
  token_budget_per_call,
  max_calls_per_session,
  cost_per_call_usd,
  is_active,
  is_degraded,
  failure_rate,
  avg_latency_ms,
  use_count,
  sort_priority,
  workspace_scope,
  schema_hint,
  notes,
  is_global,
  created_at,
  updated_at
)
VALUES (
  'browser_navigate',
  'Browser Navigate',
  'browser.navigate',
  'builtin',
  'Navigate the server-side browser to a trusted URL for live inspection, preview validation, and page testing.',
  '{"url":"string"}',
  '{"ok":"boolean","url":"string","title":"string","status":"string","error":"string"}',
  '{"dispatcher":"browser_navigate","source_file":"src/tools/builtin/web.js","requires_trusted_origin":true}',
  '["browser","navigate","open url","inspect page","preview","live route","website","debug ui"]',
  '["browser","navigation","live_page","preview","visual_qa"]',
  '["auto","agent","build","debug","test"]',
  'low',
  0,
  0,
  NULL,
  20,
  0.0,
  1,
  0,
  0.0,
  NULL,
  0,
  110,
  '["ws_inneranimalmedia"]',
  'Use when Agent Sam needs to open a trusted URL before inspecting content, taking a screenshot, or validating a live route. Prefer browser_content or playwright_screenshot after navigation.',
  'Verified handler exists in src/tools/builtin/web.js.',
  1,
  unixepoch(),
  unixepoch()
)
ON CONFLICT(tool_name) DO UPDATE SET
  display_name=excluded.display_name,
  tool_category=excluded.tool_category,
  handler_type=excluded.handler_type,
  description=excluded.description,
  input_schema=excluded.input_schema,
  output_schema=excluded.output_schema,
  handler_config=excluded.handler_config,
  intent_tags=excluded.intent_tags,
  intent_category_tags=excluded.intent_category_tags,
  modes_json=excluded.modes_json,
  risk_level=excluded.risk_level,
  requires_approval=excluded.requires_approval,
  requires_confirmation=excluded.requires_confirmation,
  token_budget_per_call=excluded.token_budget_per_call,
  max_calls_per_session=excluded.max_calls_per_session,
  cost_per_call_usd=excluded.cost_per_call_usd,
  is_active=excluded.is_active,
  is_degraded=excluded.is_degraded,
  failure_rate=excluded.failure_rate,
  avg_latency_ms=excluded.avg_latency_ms,
  sort_priority=excluded.sort_priority,
  workspace_scope=excluded.workspace_scope,
  schema_hint=excluded.schema_hint,
  notes=excluded.notes,
  is_global=excluded.is_global,
  updated_at=unixepoch();

INSERT INTO agentsam_tools (
  tool_name,
  display_name,
  tool_category,
  handler_type,
  description,
  input_schema,
  output_schema,
  handler_config,
  intent_tags,
  intent_category_tags,
  modes_json,
  risk_level,
  requires_approval,
  requires_confirmation,
  token_budget_per_call,
  max_calls_per_session,
  cost_per_call_usd,
  is_active,
  is_degraded,
  failure_rate,
  avg_latency_ms,
  use_count,
  sort_priority,
  workspace_scope,
  schema_hint,
  notes,
  is_global,
  created_at,
  updated_at
)
VALUES (
  'browser_content',
  'Browser Content Extract',
  'browser.inspect',
  'builtin',
  'Extract readable page content, headings, links, and lightweight DOM/page evidence from a trusted URL.',
  '{"url":"string","selector":"string"}',
  '{"ok":"boolean","url":"string","title":"string","content":"string","headings":"array","links":"array","error":"string"}',
  '{"dispatcher":"browser_content","source_file":"src/tools/builtin/web.js","requires_trusted_origin":true}',
  '["browser","content","inspect","read page","dom","headings","links","debug route","website qa"]',
  '["browser","inspection","live_page","dom","content","visual_qa"]',
  '["auto","agent","build","debug","test"]',
  'low',
  0,
  0,
  NULL,
  30,
  0.0,
  1,
  0,
  0.0,
  NULL,
  0,
  111,
  '["ws_inneranimalmedia"]',
  'Use when Agent Sam needs evidence from a live page without relying on screenshots alone. Good for verifying text, headings, links, loaded routes, and page structure.',
  'Verified handler exists in src/tools/builtin/web.js.',
  1,
  unixepoch(),
  unixepoch()
)
ON CONFLICT(tool_name) DO UPDATE SET
  display_name=excluded.display_name,
  tool_category=excluded.tool_category,
  handler_type=excluded.handler_type,
  description=excluded.description,
  input_schema=excluded.input_schema,
  output_schema=excluded.output_schema,
  handler_config=excluded.handler_config,
  intent_tags=excluded.intent_tags,
  intent_category_tags=excluded.intent_category_tags,
  modes_json=excluded.modes_json,
  risk_level=excluded.risk_level,
  requires_approval=excluded.requires_approval,
  requires_confirmation=excluded.requires_confirmation,
  token_budget_per_call=excluded.token_budget_per_call,
  max_calls_per_session=excluded.max_calls_per_session,
  cost_per_call_usd=excluded.cost_per_call_usd,
  is_active=excluded.is_active,
  is_degraded=excluded.is_degraded,
  failure_rate=excluded.failure_rate,
  avg_latency_ms=excluded.avg_latency_ms,
  sort_priority=excluded.sort_priority,
  workspace_scope=excluded.workspace_scope,
  schema_hint=excluded.schema_hint,
  notes=excluded.notes,
  is_global=excluded.is_global,
  updated_at=unixepoch();

INSERT INTO agentsam_tools (
  tool_name,
  display_name,
  tool_category,
  handler_type,
  description,
  input_schema,
  output_schema,
  handler_config,
  intent_tags,
  intent_category_tags,
  modes_json,
  risk_level,
  requires_approval,
  requires_confirmation,
  token_budget_per_call,
  max_calls_per_session,
  cost_per_call_usd,
  is_active,
  is_degraded,
  failure_rate,
  avg_latency_ms,
  use_count,
  sort_priority,
  workspace_scope,
  schema_hint,
  notes,
  is_global,
  created_at,
  updated_at
)
VALUES (
  'playwright_screenshot',
  'Playwright Screenshot',
  'browser.capture',
  'builtin',
  'Capture a screenshot of a trusted URL for visual proof, layout review, and UI debugging.',
  '{"url":"string","fullPage":"boolean","selector":"string"}',
  '{"ok":"boolean","url":"string","screenshot_url":"string","r2_key":"string","summary":"string","error":"string"}',
  '{"dispatcher":"playwright_screenshot","source_file":"src/tools/builtin/web.js","also_referenced_in":"src/tools/ai-dispatch.js","requires_trusted_origin":true}',
  '["browser","screenshot","visual proof","layout","ui debug","preview","website qa","inspect page"]',
  '["browser","screenshot","capture","visual_qa","layout_debug","preview"]',
  '["auto","agent","build","debug","test"]',
  'low',
  0,
  0,
  NULL,
  15,
  0.002,
  1,
  0,
  0.0,
  NULL,
  0,
  112,
  '["ws_inneranimalmedia"]',
  'Use when the user asks what a page looks like, asks Agent Sam to visually inspect something, validate layout, capture proof, or debug a UI issue.',
  'Verified handler exists in src/tools/builtin/web.js and routing reference exists in src/tools/ai-dispatch.js.',
  1,
  unixepoch(),
  unixepoch()
)
ON CONFLICT(tool_name) DO UPDATE SET
  display_name=excluded.display_name,
  tool_category=excluded.tool_category,
  handler_type=excluded.handler_type,
  description=excluded.description,
  input_schema=excluded.input_schema,
  output_schema=excluded.output_schema,
  handler_config=excluded.handler_config,
  intent_tags=excluded.intent_tags,
  intent_category_tags=excluded.intent_category_tags,
  modes_json=excluded.modes_json,
  risk_level=excluded.risk_level,
  requires_approval=excluded.requires_approval,
  requires_confirmation=excluded.requires_confirmation,
  token_budget_per_call=excluded.token_budget_per_call,
  max_calls_per_session=excluded.max_calls_per_session,
  cost_per_call_usd=excluded.cost_per_call_usd,
  is_active=excluded.is_active,
  is_degraded=excluded.is_degraded,
  failure_rate=excluded.failure_rate,
  avg_latency_ms=excluded.avg_latency_ms,
  sort_priority=excluded.sort_priority,
  workspace_scope=excluded.workspace_scope,
  schema_hint=excluded.schema_hint,
  notes=excluded.notes,
  is_global=excluded.is_global,
  updated_at=unixepoch();
