-- Seed Agent Sam's primary chat-led autonomous workflow.
-- Apply:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./migrations/318_seed_agent_universal_autonomous_run.sql

INSERT OR IGNORE INTO agentsam_workflows (
  id,
  tenant_id,
  workspace_id,
  workflow_key,
  display_name,
  description,
  workflow_type,
  trigger_type,
  default_mode,
  default_task_type,
  risk_level,
  requires_approval,
  max_concurrent_nodes,
  timeout_ms,
  quality_gate_json,
  metadata_json,
  is_active,
  is_platform_global
) VALUES (
  'wf_agent_universal_autonomous_run',
  NULL,
  NULL,
  'agent_universal_autonomous_run',
  'Agent Sam Universal Autonomous Run',
  'Primary chat-led Agent Sam workflow. It understands a natural language request, discovers available capabilities, builds a dynamic plan, executes selected tools step by step, observes results, gates risky actions for approval, and persists the full run ledger.',
  'agentic',
  'agent',
  'agent',
  'universal_autonomous_run',
  'medium',
  0,
  1,
  900000,
  '{"requires_structured_output":true,"capture_tokens":true,"capture_cost":true,"persist_step_results":true,"approval_only_for_high_risk":true,"max_steps_required":true,"max_tokens_required":true,"max_cost_required":true}',
  '{"primary_experience":true,"entrypoint":"POST /api/agent/chat","runtime_loop":["understand_request","discover_capabilities","build_execution_plan","approval_gate_if_needed","execute_next_step","observe_result","decide_continue_or_finish","persist_final_answer"],"loop_controller":{"node":"execute_next_step","observed_by":"observe_result","decision_node":"decide_continue_or_finish","handler_owned_loop":true,"continue_until":["task_complete","max_steps_reached","max_cost_reached","max_tokens_reached","approval_required","unrecoverable_error"]},"models":{"classification":"gpt-5.4-nano","risk_scoring":"gpt-5.4-nano","tool_selection":"gpt-5.4-nano","output_validation":"gpt-5.4-nano","planning":"gpt-5.4-mini","code_reasoning":"gpt-5.4-mini","browser_debug":"gpt-5.4-mini","documentation":"gpt-5.4-mini","patch_planning":"gpt-5.4-mini","pro_enabled":false},"capability_sources":["agentsam_tools","agentsam_mcp_tools","agentsam_commands","agentsam_scripts","browser_tools","db_tools","terminal_tools","r2_tools","github_tools","openai_tools"],"ui":{"route":"/dashboard/agent","show":["chat_thread","current_run","generated_plan","active_step","selected_tool","tool_result","tokens_cost","approval_gates","final_answer","raw_run_inspector"]},"production_real":true}',
  1,
  1
);

INSERT OR IGNORE INTO agentsam_workflow_nodes (
  workflow_id,
  node_key,
  node_type,
  title,
  description,
  handler_key,
  input_schema_json,
  output_schema_json,
  timeout_ms,
  retry_policy_json,
  quality_gate_json,
  risk_level,
  requires_approval,
  is_active,
  sort_order
) VALUES
  (
    'wf_agent_universal_autonomous_run',
    'understand_request',
    'agent',
    'Understand Request',
    'Classify the user request, intent, risk level, likely output type, and whether approval may be needed.',
    'openai.nano.understand_request',
    '{"type":"object","required":["message"],"properties":{"message":{"type":"string"},"context":{"type":"object"}}}',
    '{"type":"object","required":["intent","risk_level","output_type"],"properties":{"intent":{"type":"string"},"risk_level":{"type":"string"},"output_type":{"type":"string"},"needs_tools":{"type":"boolean"}}}',
    60000,
    '{"max_retries":1,"backoff":"exponential","delay_ms":1000}',
    '{"model":"gpt-5.4-nano","prohibited_models":["gpt-5.4-pro"]}',
    'low',
    0,
    1,
    10
  ),
  (
    'wf_agent_universal_autonomous_run',
    'discover_capabilities',
    'db_query',
    'Discover Capabilities',
    'Read the available tool, MCP, command, script, browser, database, terminal, R2, GitHub, and model capabilities before selecting actions.',
    'registry.discover_agent_capabilities',
    '{"type":"object","properties":{"intent":{"type":"string"},"risk_level":{"type":"string"}}}',
    '{"type":"object","properties":{"tools":{"type":"array"},"models":{"type":"array"},"commands":{"type":"array"},"scripts":{"type":"array"}}}',
    60000,
    '{"max_retries":1,"backoff":"exponential","delay_ms":1000}',
    '{"must_use_registry":true,"sources":["agentsam_tools","agentsam_mcp_tools","agentsam_commands","agentsam_scripts"]}',
    'low',
    0,
    1,
    20
  ),
  (
    'wf_agent_universal_autonomous_run',
    'build_execution_plan',
    'agent',
    'Build Execution Plan',
    'Generate a dynamic step plan from the classified request and the discovered capability registry.',
    'openai.mini.build_execution_plan',
    '{"type":"object","properties":{"request":{"type":"object"},"capabilities":{"type":"object"}}}',
    '{"type":"object","required":["plan","budget"],"properties":{"plan":{"type":"array"},"budget":{"type":"object"},"approval_gates":{"type":"array"}}}',
    90000,
    '{"max_retries":1,"backoff":"exponential","delay_ms":1000}',
    '{"model":"gpt-5.4-mini","requires_dynamic_plan":true,"prohibited_models":["gpt-5.4-pro"]}',
    'medium',
    0,
    1,
    30
  ),
  (
    'wf_agent_universal_autonomous_run',
    'approval_gate_if_needed',
    'branch',
    'Approval Gate If Needed',
    'Pause only when the planned or next action is high risk, destructive, deploy-affecting, credential-touching, or above configured budget.',
    'approval.dynamic_risk_budget_gate',
    '{"type":"object","properties":{"plan":{"type":"array"},"risk_level":{"type":"string"},"budget":{"type":"object"}}}',
    '{"type":"object","properties":{"approved":{"type":"boolean"},"approval_required":{"type":"boolean"},"reason":{"type":"string"}}}',
    30000,
    '{"max_retries":0}',
    '{"approval_only_when_high_risk":true,"risk_levels_requiring_pause":["high","critical"]}',
    'medium',
    0,
    1,
    40
  ),
  (
    'wf_agent_universal_autonomous_run',
    'execute_next_step',
    'agent',
    'Execute Next Step',
    'Run the next selected tool, model, script, browser, database, terminal, R2, GitHub, artifact, email, or MCP action from the dynamic plan.',
    'agent_loop.execute_next_step',
    '{"type":"object","properties":{"plan":{"type":"array"},"cursor":{"type":"integer"},"capabilities":{"type":"object"},"budgets":{"type":"object"}}}',
    '{"type":"object","properties":{"tool_key":{"type":"string"},"tool_type":{"type":"string"},"result":{"type":"object"},"usage":{"type":"object"},"risk_level":{"type":"string"}}}',
    180000,
    '{"max_retries":2,"backoff":"exponential","delay_ms":1000}',
    '{"persist_every_step":true,"capture_tokens":true,"capture_cost":true,"handler_owned_loop":true}',
    'medium',
    0,
    1,
    50
  ),
  (
    'wf_agent_universal_autonomous_run',
    'observe_result',
    'agent',
    'Observe Result',
    'Normalize tool output, errors, artifacts, validation evidence, usage, and state changes into a ledger-ready observation.',
    'openai.nano.observe_result',
    '{"type":"object","properties":{"tool_result":{"type":"object"},"prior_state":{"type":"object"}}}',
    '{"type":"object","properties":{"observation":{"type":"string"},"state_delta":{"type":"object"},"usage":{"type":"object"},"error":{"type":"string"}}}',
    60000,
    '{"max_retries":1,"backoff":"exponential","delay_ms":1000}',
    '{"model":"gpt-5.4-nano","normalize_result":true,"prohibited_models":["gpt-5.4-pro"]}',
    'low',
    0,
    1,
    60
  ),
  (
    'wf_agent_universal_autonomous_run',
    'decide_continue_or_finish',
    'branch',
    'Decide Continue Or Finish',
    'Decide whether to continue, retry, branch, ask approval, stop on budget, stop on unrecoverable error, or finalize.',
    'agent_loop.decide_continue_or_finish',
    '{"type":"object","properties":{"observation":{"type":"object"},"plan_state":{"type":"object"},"budgets":{"type":"object"}}}',
    '{"type":"object","properties":{"decision":{"type":"string"},"next_step":{"type":"object"},"kill_reason":{"type":"string"},"complete":{"type":"boolean"}}}',
    30000,
    '{"max_retries":0}',
    '{"stop_conditions":["task_complete","max_steps_reached","max_cost_reached","max_tokens_reached","approval_required","unrecoverable_error"]}',
    'low',
    0,
    1,
    70
  ),
  (
    'wf_agent_universal_autonomous_run',
    'persist_final_answer',
    'agent',
    'Persist Final Answer',
    'Save output_json, final answer, model usage, cost, duration, kill reason, and validation evidence for the user and run inspector.',
    'agent_loop.persist_final_answer',
    '{"type":"object","properties":{"plan_state":{"type":"object"},"step_results":{"type":"array"},"final_answer":{"type":"string"}}}',
    '{"type":"object","properties":{"final_answer":{"type":"string"},"output_json":{"type":"object"},"usage":{"type":"object"}}}',
    60000,
    '{"max_retries":1,"backoff":"exponential","delay_ms":1000}',
    '{"persist_output_json":true,"persist_step_results_json":true,"mirror_supabase_when_available":true}',
    'low',
    0,
    1,
    80
  );

INSERT OR IGNORE INTO agentsam_workflow_edges (
  workflow_id,
  from_node_key,
  to_node_key,
  condition_type,
  priority,
  label
) VALUES
  ('wf_agent_universal_autonomous_run', 'understand_request', 'discover_capabilities', 'always', 10, 'understand_request -> discover_capabilities'),
  ('wf_agent_universal_autonomous_run', 'discover_capabilities', 'build_execution_plan', 'always', 20, 'discover_capabilities -> build_execution_plan'),
  ('wf_agent_universal_autonomous_run', 'build_execution_plan', 'approval_gate_if_needed', 'always', 30, 'build_execution_plan -> approval_gate_if_needed'),
  ('wf_agent_universal_autonomous_run', 'approval_gate_if_needed', 'execute_next_step', 'always', 40, 'approval_gate_if_needed -> execute_next_step'),
  ('wf_agent_universal_autonomous_run', 'execute_next_step', 'observe_result', 'always', 50, 'execute_next_step -> observe_result'),
  ('wf_agent_universal_autonomous_run', 'observe_result', 'decide_continue_or_finish', 'always', 60, 'observe_result -> decide_continue_or_finish'),
  ('wf_agent_universal_autonomous_run', 'decide_continue_or_finish', 'persist_final_answer', 'always', 70, 'decide_continue_or_finish -> persist_final_answer');
