-- 319: Platform Wrangler commands for Cmd+K (agentsam_commands)
-- Apply: ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./migrations/319_seed_wrangler_cmdk_commands.sql

INSERT INTO agentsam_commands (
  id, workspace_id, slug, display_name, description, category,
  mapped_command, risk_level, requires_confirmation, show_in_palette,
  sort_order, is_active, execution_mode, router_type
) VALUES
('cmd_wr_r2-bucket-create', 'platform', '/wr/r2-bucket-create', 'R2 bucket create', NULL, 'r2', 'wrangler r2 bucket create <NAME>', 'medium', 1, 1, 10, 1, 'agent', 'tool'),
('cmd_wr_r2-bucket-list', 'platform', '/wr/r2-bucket-list', 'R2 bucket list', NULL, 'r2', 'wrangler r2 bucket list', 'low', 0, 1, 11, 1, 'agent', 'tool'),
('cmd_wr_r2-bucket-delete', 'platform', '/wr/r2-bucket-delete', 'R2 bucket delete', NULL, 'r2', 'wrangler r2 bucket delete <NAME>', 'high', 1, 1, 12, 1, 'agent', 'tool'),
('cmd_wr_r2-bucket-info', 'platform', '/wr/r2-bucket-info', 'R2 bucket info', NULL, 'r2', 'wrangler r2 bucket info <NAME>', 'low', 0, 1, 13, 1, 'agent', 'tool'),
('cmd_wr_r2-object-get', 'platform', '/wr/r2-object-get', 'R2 object get', NULL, 'r2', 'wrangler r2 object get <BUCKET>/<KEY> --file=<OUTPUT>', 'low', 0, 1, 14, 1, 'agent', 'tool'),
('cmd_wr_r2-object-put', 'platform', '/wr/r2-object-put', 'R2 object put', NULL, 'r2', 'wrangler r2 object put <BUCKET>/<KEY> --file=<INPUT>', 'medium', 1, 1, 15, 1, 'agent', 'tool'),
('cmd_wr_r2-object-delete', 'platform', '/wr/r2-object-delete', 'R2 object delete', NULL, 'r2', 'wrangler r2 object delete <BUCKET>/<KEY>', 'high', 1, 1, 16, 1, 'agent', 'tool'),
('cmd_wr_r2-object-list', 'platform', '/wr/r2-object-list', 'R2 object list', NULL, 'r2', 'wrangler r2 object list <BUCKET> --prefix=<PREFIX>', 'low', 0, 1, 17, 1, 'agent', 'tool'),
('cmd_wr_d1-create', 'platform', '/wr/d1-create', 'D1 create', NULL, 'd1', 'wrangler d1 create <NAME>', 'medium', 1, 1, 20, 1, 'agent', 'tool'),
('cmd_wr_d1-list', 'platform', '/wr/d1-list', 'D1 list', NULL, 'd1', 'wrangler d1 list', 'low', 0, 1, 21, 1, 'agent', 'tool'),
('cmd_wr_d1-info', 'platform', '/wr/d1-info', 'D1 info', NULL, 'd1', 'wrangler d1 info <NAME>', 'low', 0, 1, 22, 1, 'agent', 'tool'),
('cmd_wr_d1-delete', 'platform', '/wr/d1-delete', 'D1 delete', NULL, 'd1', 'wrangler d1 delete <NAME>', 'high', 1, 1, 23, 1, 'agent', 'tool'),
('cmd_wr_d1-execute-cmd', 'platform', '/wr/d1-execute-cmd', 'D1 execute (SQL)', NULL, 'd1', 'wrangler d1 execute <NAME> --command="<SQL>" --remote', 'low', 0, 1, 24, 1, 'agent', 'tool'),
('cmd_wr_d1-execute-file', 'platform', '/wr/d1-execute-file', 'D1 execute (file)', NULL, 'd1', 'wrangler d1 execute <NAME> --file=<FILE> --remote', 'low', 0, 1, 25, 1, 'agent', 'tool'),
('cmd_wr_d1-export', 'platform', '/wr/d1-export', 'D1 export backup', NULL, 'd1', 'wrangler d1 export <NAME> --remote --output=backup.sql', 'medium', 1, 1, 26, 1, 'agent', 'tool'),
('cmd_wr_d1-export-schema', 'platform', '/wr/d1-export-schema', 'D1 export schema', NULL, 'd1', 'wrangler d1 export <NAME> --remote --output=schema.sql --no-data', 'medium', 1, 1, 27, 1, 'agent', 'tool'),
('cmd_wr_d1-migrations-create', 'platform', '/wr/d1-migrations-create', 'D1 migrations create', NULL, 'd1', 'wrangler d1 migrations create <NAME> <MIGRATION_NAME>', 'medium', 1, 1, 28, 1, 'agent', 'tool'),
('cmd_wr_d1-migrations-list', 'platform', '/wr/d1-migrations-list', 'D1 migrations list', NULL, 'd1', 'wrangler d1 migrations list <NAME> --remote', 'low', 0, 1, 29, 1, 'agent', 'tool'),
('cmd_wr_d1-migrations-apply', 'platform', '/wr/d1-migrations-apply', 'D1 migrations apply', NULL, 'd1', 'wrangler d1 migrations apply <NAME> --remote', 'medium', 1, 1, 30, 1, 'agent', 'tool'),
('cmd_wr_vectorize-create-dims', 'platform', '/wr/vectorize-create-dims', 'Vectorize create (dimensions)', NULL, 'vectorize', 'wrangler vectorize create <NAME> --dimensions=<N> --metric=cosine', 'medium', 1, 1, 40, 1, 'agent', 'tool'),
('cmd_wr_vectorize-create-preset', 'platform', '/wr/vectorize-create-preset', 'Vectorize create (preset)', NULL, 'vectorize', 'wrangler vectorize create <NAME> --preset=@cf/baai/bge-base-en-v1.5', 'medium', 1, 1, 41, 1, 'agent', 'tool'),
('cmd_wr_vectorize-list', 'platform', '/wr/vectorize-list', 'Vectorize list', NULL, 'vectorize', 'wrangler vectorize list', 'low', 0, 1, 42, 1, 'agent', 'tool'),
('cmd_wr_vectorize-get', 'platform', '/wr/vectorize-get', 'Vectorize get', NULL, 'vectorize', 'wrangler vectorize get <NAME>', 'low', 0, 1, 43, 1, 'agent', 'tool'),
('cmd_wr_vectorize-delete', 'platform', '/wr/vectorize-delete', 'Vectorize delete', NULL, 'vectorize', 'wrangler vectorize delete <NAME>', 'high', 1, 1, 44, 1, 'agent', 'tool'),
('cmd_wr_vectorize-insert', 'platform', '/wr/vectorize-insert', 'Vectorize insert', NULL, 'vectorize', 'wrangler vectorize insert <NAME> --file=vectors.ndjson', 'medium', 1, 1, 45, 1, 'agent', 'tool'),
('cmd_wr_vectorize-query', 'platform', '/wr/vectorize-query', 'Vectorize query', NULL, 'vectorize', 'wrangler vectorize query <NAME> --vector="[0.1, 0.2, ...]" --top-k=10', 'low', 0, 1, 46, 1, 'agent', 'tool'),
('cmd_wr_hyperdrive-create', 'platform', '/wr/hyperdrive-create', 'Hyperdrive create', NULL, 'hyperdrive', 'wrangler hyperdrive create <NAME> --connection-string="postgres://user:pass@host:5432/db"', 'medium', 1, 1, 50, 1, 'agent', 'tool'),
('cmd_wr_hyperdrive-list', 'platform', '/wr/hyperdrive-list', 'Hyperdrive list', NULL, 'hyperdrive', 'wrangler hyperdrive list', 'low', 0, 1, 51, 1, 'agent', 'tool'),
('cmd_wr_hyperdrive-get', 'platform', '/wr/hyperdrive-get', 'Hyperdrive get', NULL, 'hyperdrive', 'wrangler hyperdrive get <ID>', 'low', 0, 1, 52, 1, 'agent', 'tool'),
('cmd_wr_hyperdrive-update', 'platform', '/wr/hyperdrive-update', 'Hyperdrive update', NULL, 'hyperdrive', 'wrangler hyperdrive update <ID> --connection-string="..."', 'medium', 1, 1, 53, 1, 'agent', 'tool'),
('cmd_wr_hyperdrive-delete', 'platform', '/wr/hyperdrive-delete', 'Hyperdrive delete', NULL, 'hyperdrive', 'wrangler hyperdrive delete <ID>', 'high', 1, 1, 54, 1, 'agent', 'tool'),
('cmd_wr_kv-namespace-create', 'platform', '/wr/kv-namespace-create', 'KV namespace create', NULL, 'kv', 'wrangler kv namespace create <NAME>', 'medium', 1, 1, 60, 1, 'agent', 'tool'),
('cmd_wr_kv-namespace-list', 'platform', '/wr/kv-namespace-list', 'KV namespace list', NULL, 'kv', 'wrangler kv namespace list', 'low', 0, 1, 61, 1, 'agent', 'tool'),
('cmd_wr_kv-namespace-delete', 'platform', '/wr/kv-namespace-delete', 'KV namespace delete', NULL, 'kv', 'wrangler kv namespace delete --namespace-id=<ID>', 'high', 1, 1, 62, 1, 'agent', 'tool'),
('cmd_wr_kv-key-put', 'platform', '/wr/kv-key-put', 'KV key put', NULL, 'kv', 'wrangler kv key put <KEY> <VALUE> --namespace-id=<ID> --remote', 'medium', 1, 1, 63, 1, 'agent', 'tool'),
('cmd_wr_kv-key-get', 'platform', '/wr/kv-key-get', 'KV key get', NULL, 'kv', 'wrangler kv key get <KEY> --namespace-id=<ID> --remote', 'low', 0, 1, 64, 1, 'agent', 'tool'),
('cmd_wr_kv-key-delete', 'platform', '/wr/kv-key-delete', 'KV key delete', NULL, 'kv', 'wrangler kv key delete <KEY> --namespace-id=<ID> --remote', 'high', 1, 1, 65, 1, 'agent', 'tool'),
('cmd_wr_kv-key-list', 'platform', '/wr/kv-key-list', 'KV key list', NULL, 'kv', 'wrangler kv key list --namespace-id=<ID> --remote', 'low', 0, 1, 66, 1, 'agent', 'tool'),
('cmd_wr_queues-create', 'platform', '/wr/queues-create', 'Queues create', NULL, 'queues', 'wrangler queues create <NAME>', 'medium', 1, 1, 70, 1, 'agent', 'tool'),
('cmd_wr_queues-list', 'platform', '/wr/queues-list', 'Queues list', NULL, 'queues', 'wrangler queues list', 'low', 0, 1, 71, 1, 'agent', 'tool'),
('cmd_wr_queues-delete', 'platform', '/wr/queues-delete', 'Queues delete', NULL, 'queues', 'wrangler queues delete <NAME>', 'high', 1, 1, 72, 1, 'agent', 'tool'),
('cmd_wr_queues-consumer-add', 'platform', '/wr/queues-consumer-add', 'Queues consumer add', NULL, 'queues', 'wrangler queues consumer add <QUEUE> <WORKER>', 'low', 0, 1, 73, 1, 'agent', 'tool'),
('cmd_wr_queues-consumer-remove', 'platform', '/wr/queues-consumer-remove', 'Queues consumer remove', NULL, 'queues', 'wrangler queues consumer remove <QUEUE> <WORKER>', 'high', 1, 1, 74, 1, 'agent', 'tool'),
('cmd_wr_worker-deploy', 'platform', '/wr/worker-deploy', 'Deploy Worker', 'Deploy current Worker project', 'worker', 'wrangler deploy', 'medium', 1, 1, 80, 1, 'agent', 'tool'),
('cmd_wr_worker-dev', 'platform', '/wr/worker-dev', 'Dev server', NULL, 'worker', 'wrangler dev', 'low', 0, 1, 81, 1, 'agent', 'tool'),
('cmd_wr_worker-tail', 'platform', '/wr/worker-tail', 'Tail logs', NULL, 'worker', 'wrangler tail <WORKER_NAME>', 'low', 0, 1, 82, 1, 'agent', 'tool'),
('cmd_wr_worker-rollback', 'platform', '/wr/worker-rollback', 'Rollback', NULL, 'worker', 'wrangler rollback', 'high', 1, 1, 83, 1, 'agent', 'tool'),
('cmd_wr_worker-versions-list', 'platform', '/wr/worker-versions-list', 'Versions list', NULL, 'worker', 'wrangler versions list', 'low', 0, 1, 84, 1, 'agent', 'tool'),
('cmd_wr_worker-versions-deploy', 'platform', '/wr/worker-versions-deploy', 'Versions deploy', NULL, 'worker', 'wrangler versions deploy', 'medium', 1, 1, 85, 1, 'agent', 'tool'),
('cmd_wr_worker-secret-put', 'platform', '/wr/worker-secret-put', 'Secret put', NULL, 'worker', 'wrangler secret put <NAME>', 'medium', 1, 1, 86, 1, 'agent', 'tool'),
('cmd_wr_worker-secret-delete', 'platform', '/wr/worker-secret-delete', 'Secret delete', NULL, 'worker', 'wrangler secret delete <NAME>', 'high', 1, 1, 87, 1, 'agent', 'tool'),
('cmd_wr_worker-secret-list', 'platform', '/wr/worker-secret-list', 'Secret list', NULL, 'worker', 'wrangler secret list', 'low', 0, 1, 88, 1, 'agent', 'tool'),
('cmd_wr_worker-whoami', 'platform', '/wr/worker-whoami', 'Whoami', NULL, 'worker', 'wrangler whoami', 'low', 0, 1, 89, 1, 'agent', 'tool'),
('cmd_wr_worker-login', 'platform', '/wr/worker-login', 'Login', NULL, 'worker', 'wrangler login', 'low', 0, 1, 90, 1, 'agent', 'tool'),
('cmd_wr_worker-logout', 'platform', '/wr/worker-logout', 'Logout', NULL, 'worker', 'wrangler logout', 'low', 0, 1, 91, 1, 'agent', 'tool'),
('cmd_wr_workflows-list', 'platform', '/wr/workflows-list', 'Workflows list', NULL, 'workflows', 'wrangler workflows list', 'low', 0, 1, 100, 1, 'agent', 'tool'),
('cmd_wr_workflows-describe', 'platform', '/wr/workflows-describe', 'Workflows describe', NULL, 'workflows', 'wrangler workflows describe <NAME>', 'low', 0, 1, 101, 1, 'agent', 'tool'),
('cmd_wr_workflows-trigger', 'platform', '/wr/workflows-trigger', 'Workflows trigger', NULL, 'workflows', 'wrangler workflows trigger <NAME>', 'medium', 1, 1, 102, 1, 'agent', 'tool'),
('cmd_wr_workflows-instances-list', 'platform', '/wr/workflows-instances-list', 'Workflow instances list', NULL, 'workflows', 'wrangler workflows instances list <NAME>', 'low', 0, 1, 103, 1, 'agent', 'tool'),
('cmd_wr_workflows-instances-describe', 'platform', '/wr/workflows-instances-describe', 'Workflow instance describe', NULL, 'workflows', 'wrangler workflows instances describe <NAME> <INSTANCE_ID>', 'low', 0, 1, 104, 1, 'agent', 'tool'),
('cmd_wr_workflows-instances-terminate', 'platform', '/wr/workflows-instances-terminate', 'Workflow instance terminate', NULL, 'workflows', 'wrangler workflows instances terminate <NAME> <INSTANCE_ID>', 'high', 1, 1, 105, 1, 'agent', 'tool')
ON CONFLICT(id) DO UPDATE SET
  workspace_id = excluded.workspace_id,
  slug = excluded.slug,
  display_name = excluded.display_name,
  description = excluded.description,
  category = excluded.category,
  mapped_command = excluded.mapped_command,
  risk_level = excluded.risk_level,
  requires_confirmation = excluded.requires_confirmation,
  show_in_palette = excluded.show_in_palette,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  execution_mode = excluded.execution_mode,
  router_type = excluded.router_type,
  updated_at = datetime('now');
