-- Platform-global Quickstart gallery (is_platform_global = 1).
-- Served by GET /api/agent/quickstart/templates — no dashboard deploy to add cards.
--
-- Run:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./migrations/352_seed_quickstart_platform_subagents.sql

INSERT INTO agentsam_subagent_profile (
  id,
  user_id,
  workspace_id,
  tenant_id,
  slug,
  display_name,
  description,
  instructions_markdown,
  allowed_tool_globs,
  default_model_id,
  is_active,
  is_platform_global,
  sort_order,
  agent_type,
  output_schema_json,
  created_at,
  updated_at
) VALUES
(
  'qs_tpl_deep_researcher',
  'platform',
  '',
  '',
  'deep-researcher',
  'Deep researcher',
  'Multi-step research with sources, synthesis, and gap analysis.',
  'Quickstart: Deep researcher. Help me investigate a topic with sub-questions, cited sources, and a confidence-scored summary. Ask what topic to research if I have not specified one.',
  '["read","glob","grep","web"]',
  NULL,
  1,
  1,
  10,
  'research',
  '{"quickstart":{"task_type":"web_search","route_key":"chat","model_hint":"claude-sonnet-4-6"}}',
  datetime('now'),
  datetime('now')
),
(
  'qs_tpl_code_editor',
  'platform',
  '',
  '',
  'code-editor',
  'Code editor',
  'Implement, refactor, and fix code in this workspace with Monaco and terminal tools.',
  'Quickstart: Code editor. I want to implement or fix something in this repo. Ask what file or feature to touch, then use workspace read/search and terminal only when needed.',
  '["read","write","glob","grep","terminal"]',
  NULL,
  1,
  1,
  20,
  'code',
  '{"quickstart":{"task_type":"code","route_key":"code","model_hint":"claude-sonnet-4-6"}}',
  datetime('now'),
  datetime('now')
),
(
  'qs_tpl_deploy_validator',
  'platform',
  '',
  '',
  'deploy-validator',
  'Deploy validator',
  'Health check, dashboard asset integrity, and deploy proof — not health-only.',
  'Quickstart: Deploy validator. Walk me through validating a deploy: Worker /health, dashboard HTML chunk 200s, and browser proof. Ask which surface we are shipping.',
  '["read","terminal","browser"]',
  'gemini-2.5-flash-lite',
  1,
  1,
  30,
  'deploy',
  '{"quickstart":{"task_type":"deploy","route_key":"deploy_validation","model_hint":"gemini-2.5-flash-lite"}}',
  datetime('now'),
  datetime('now')
),
(
  'qs_tpl_model_compare',
  'platform',
  '',
  '',
  'model-compare',
  'Model compare',
  'Run the same prompt across models and compare latency, cost, and quality.',
  'Quickstart: Model compare. I will give you one prompt — help me run it fairly across 2–3 models and summarize tokens, cost, and quality. Ask for the prompt if missing.',
  '["read"]',
  NULL,
  1,
  1,
  40,
  'eval',
  '{"quickstart":{"task_type":"chat","route_key":"model_comparison","model_hint":"Thompson routing"}}',
  datetime('now'),
  datetime('now')
)
ON CONFLICT(user_id, workspace_id, slug) DO UPDATE SET
  display_name = excluded.display_name,
  description = excluded.description,
  instructions_markdown = excluded.instructions_markdown,
  allowed_tool_globs = excluded.allowed_tool_globs,
  default_model_id = excluded.default_model_id,
  is_active = excluded.is_active,
  is_platform_global = excluded.is_platform_global,
  sort_order = excluded.sort_order,
  agent_type = excluded.agent_type,
  output_schema_json = excluded.output_schema_json,
  updated_at = datetime('now');
