-- CMS editor test/challenger repo — local path + dual-runtime Workers (TS stable + Python challenger).
-- Apply:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./migrations/377_agentsam_project_context_cms_editor_repo.sql

INSERT OR REPLACE INTO agentsam_project_context (
  id,
  tenant_id,
  workspace_id,
  project_key,
  project_name,
  project_type,
  status,
  priority,
  description,
  goals,
  constraints,
  current_blockers,
  primary_tables,
  secondary_tables,
  workers_involved,
  r2_buckets_involved,
  domains_involved,
  key_files,
  related_routes,
  linked_plan_id,
  created_by,
  notes,
  started_at,
  created_at,
  updated_at
) VALUES (
  'ctx_agentsam_cms_editor_repo_20260523',
  'tenant_sam_primeaux',
  'ws_inneranimalmedia',
  'agentsam-cms-editor',
  'Agent Sam CMS Editor — test / challenger repo',
  'worker_repo',
  'active',
  72,
  'Standalone CMS analytics + editor buildout repo (GitHub: SamPrimeaux/agentsam-cms-editor). Local checkout: cd /Users/samprimeaux/agentsam-cms-editor — use this path for all terminal work, wrangler deploy, and Python/TS Worker changes in this program. Dual runtime: agentsam-cms-editor (TypeScript, wrangler.toml) and agentsam-cms-python (Python, wrangler.python.toml). Parent IAM repo remains /Users/samprimeaux/inneranimalmedia.',
  '["Ship portable analytics dashboard (analytics-app/)","Dual-runtime Thompson routing (cms_routing arms)","Schema gap remediation vs shared D1 inneranimalmedia-business","Router Worker agentsam-cms-router (future)"]',
  '["Repo root ONLY: /Users/samprimeaux/agentsam-cms-editor","Do NOT use ~/Downloads/inneranimalmedia or inneranimalmedia-agentsam-dashboard (removed)","CF Builds on main deploys TS only; Python via npm run deploy:python","Shared D1: inneranimalmedia-business — registry-driven, no hardcoded workflow keys in app logic"]',
  '["Router Worker not deployed yet","112 D1 tables not referenced in cms-editor repo (plan_54203057136a)"]',
  '["agentsam_routing_arms","agentsam_workflow_handlers","agentsam_workflows","agentsam_workflow_nodes","agentsam_workflow_edges","agentsam_cookbook"]',
  '["agentsam_workflow_runs","agentsam_eval_runs","agentsam_usage_events","agentsam_plans","agentsam_plan_tasks"]',
  '["agentsam-cms-editor","agentsam-cms-python"]',
  '["agent-sam","inneranimalmedia-dashboard"]',
  '["agentsam-cms-editor.meauxbility.workers.dev","agentsam-cms-python.meauxbility.workers.dev"]',
  '["wrangler.toml","wrangler.python.toml","src/index.ts","src/entry.py","analytics-app/","docs/DUAL_RUNTIME_THOMPSON.md","scripts/audit/py1_cms_editor_schema_gap_analysis.py","scripts/audit/py2_seed_thompson_arms_full.py"]',
  '["/api/analytics/overview","/api/analytics/health","/api/analytics/finance","/api/analytics/arms","/api/analytics/evals"]',
  'plan_may22_2026_agent_sam',
  'cursor_session_sync',
  'LOCAL_CD: cd /Users/samprimeaux/agentsam-cms-editor | IAM_CD: cd /Users/samprimeaux/inneranimalmedia | cms-editor main commit 126cc08; Thompson arms arm_cms_typescript/arm_cms_python; workflow wf_cms_thompson_router.',
  unixepoch(),
  unixepoch(),
  unixepoch()
);
