-- 637: Refresh canonical platform master context (ctx_inneranimalmedia).
-- Replaces outdated blockers/goals from migration 587 era (monolithic worker.js references removed).
-- Verified against repo + remote D1: 2026-06-14.
-- Apply:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business \
--     --remote -c wrangler.production.toml --file=./migrations/637_ctx_inneranimalmedia_platform_refresh.sql

UPDATE agentsam_project_context
SET
  project_name = 'inneranimalmedia Worker — Platform Master',
  project_type = 'saas-platform',
  status = 'active',
  priority = 100,
  description = 'Cloudflare Worker `inneranimalmedia` (inneranimalmedia.com). Modular entry `src/index.js` (~626 modules) — legacy `worker.js` removed; all `/api` routes dispatch via `src/core/production-dispatch.js`. Core stack: Workers + D1 `inneranimalmedia-business` (cf87b717-d4e2-4cf8-bab0-a81268e32d49) + R2 (`inneranimalmedia`, `inneranimalmedia-autorag`, `artifacts`) + KV (`KV`, `SESSION_CACHE`) + Hyperdrive Supabase pgvector (dpmuvynqixblxsilnlut, agentsam schema) + Vectorize (6 indexes: memory/codebase/schema/documents/courses @1536 OpenAI + moviemode-gemini2-1536). Durable Objects: IAMCollaborationSession, AgentChatSqlV1, AgentBrowserLiveV1, ChessRoom, MyContainer. Services: MOVIEMODE_SERVICE, PTY_SERVICE (iam-vpc). Dashboard: React/Vite SPA `dashboard/` → R2 `static/dashboard/app/`. Two repos: `/Users/samprimeaux/inneranimalmedia` (main) + `/Users/samprimeaux/inneranimalmedia-mcp-server` (MCP at mcp.inneranimalmedia.com). Agent Sam chat spine: POST /api/agent/chat → agent-chat-spine.js → runtime-profile.js → resolveModelForTask (Thompson, 277 active arms on ws_inneranimalmedia). In-app tools: dispatchByToolCode → catalog-tool-executor.js — never proxy dashboard agent through MCP worker. Per-site CMS rows: ctx_cms_* (priority 75). Client workers (e.g. companionscpas) live on separate workspaces/repos with own agentsam_project_context rows (ws_companionscpas). Auth: tenant_sam_primeaux, ws_inneranimalmedia, user au_871d920d1233cbd1. Connor McNeely: ws_connor_mcneely BYOK isolation.',
  goals = 'Runtime spine: agent-chat-spine → resolveRuntimeProfile → resolveModelForTask → agent-tool-loop with dispatchByToolCode. CMS M3: per-site ctx_cms_* + cms_pages/sections/themes/live-editor (migrations 628–633). Code indexer: agentsam_code_index_job → code-indexer.js → Supabase agentsam_codebase_chunks → AGENTSAM_VECTORIZE_CODE. Context compaction: conversation-compaction.js + r2-context-store.js digests on AUTORAG_BUCKET. Agent.js decomposition: classify-intent.js extracted; ~4742 lines remain in agent.js. DesignStudio: IAM_COLLAB collab-broadcast + ChessRoom /games WebSocket. MyContainer sandbox + agentsam_container_exec tool (635). Meet engine MEET_ENGINE=realtimekit. Client ops: separate worker repos (companionscpas sectionalized CMS handoff complete 2026-06-14).',
  constraints = 'NO emojis — platform-wide. NEVER hardcode model IDs, tenant IDs, workspace IDs, or API keys in source — resolve from D1/session at runtime. Deploy ONLY via `npm run deploy:full` from repo root — never `npm run deploy` alone for full product ship; never wrangler deploy without frontend R2 sync when dashboard changed. D1 wrangler: always `--remote -c wrangler.production.toml`. Two repos — NEVER mix deploy paths: main app `/Users/samprimeaux/inneranimalmedia`, MCP `/Users/samprimeaux/inneranimalmedia-mcp-server`. In-app Agent Sam uses dispatchByToolCode on main worker — NEVER route dashboard chat through mcp.inneranimalmedia.com. New `/api` routes: add ONLY in production-dispatch.js (router.js is barrel). Legacy worker.js and ctx_iam_worker are deleted — do not reference. Patches over rewrites; backup before editing. DB writes non-fatal (try/catch, ctx.waitUntil). agentsam_tools is sole tool catalog SSOT (agentsam_mcp_tools dropped). Superadmin bypass: user.role === superadmin. SQLite CHECK changes: rename/recreate/INSERT SELECT/DROP. INSERT OR IGNORE can silently skip on CHECK violations.',
  current_blockers = 'Agent mode can compile zero tools while still calling model (README 2026-06-01). list_dir/write_file loopback to unwired /api/fs/list and /api/fs/write. agent.js still monolithic (~4742 lines). Dashboard subset-shared.chunk.js ~737KB gzip (target <200KB). Multitask can report ok with empty subagent output. Open security audit items outstanding. Client worker changes (companionscpas, etc.) belong in client repos — not IAM platform patches.',
  primary_tables = 'agentsam_agent_run,agentsam_chat_sessions,agentsam_workspace,agentsam_workspace_state,agentsam_tools,agentsam_routing_arms,agentsam_model_catalog,agentsam_prompt_routes,agentsam_route_requirements,agentsam_project_context,agentsam_code_index_job,agentsam_context_digest,agentsam_compaction_events,agentsam_usage_rollups_daily,agentsam_tool_call_log,agentsam_workflow_runs,cms_pages,cms_page_sections,cms_themes',
  secondary_tables = 'agentsam_workspace_recent,agentsam_subagents,agentsam_memory,agentsam_skills,agentsam_routing_policy,agentsam_routing_audit,agentsam_tenant_credentials,agentsam_cron_runs,finance_transactions,deployments,agentsam_mcp_oauth_tool_allowlist,user_api_keys,user_secrets',
  workers_involved = 'inneranimalmedia,inneranimalmedia-mcp-server,moviemode-service',
  r2_buckets_involved = 'inneranimalmedia,inneranimalmedia-autorag,artifacts',
  domains_involved = 'inneranimalmedia.com,mcp.inneranimalmedia.com,webhooks.inneranimalmedia.com,artifacts.inneranimalmedia.com,inneranimals.com,meauxbility.org',
  mcp_services_involved = 'agentsam_github_read,agentsam_github_write,agentsam_github_pr,agentsam_github_issue,agentsam_d1_query,agentsam_d1_write,agentsam_d1_migrate,agentsam_r2_get,agentsam_r2_put,agentsam_r2_list,agentsam_r2_delete,agentsam_supabase_query,agentsam_supabase_write,agentsam_supabase_vector,agentsam_cf_vectorize,agentsam_memory_manager,agentsam_terminal_local,agentsam_terminal_remote,agentsam_terminal_sandbox,agentsam_send_email,agentsam_stack_deploy,agentsam_container_exec',
  key_files = 'src/index.js,src/core/production-dispatch.js,src/core/runtime-profile.js,src/core/resolveModel.js,src/core/agent-tool-loop.js,src/core/dispatch-by-tool-code.js,src/core/catalog-tool-executor.js,src/api/agent-chat-spine.js,src/api/agent.js,src/api/agent/classify-intent.js,src/core/code-indexer.js,src/core/collab-broadcast.js,src/core/r2-context-store.js,src/do/Collaboration.js,src/do/AgentChat.js,src/do/Legacy.js,dashboard/src/App.tsx,dashboard/components/ChatAssistant/ChatAssistant.tsx,wrangler.production.toml,migrations/',
  related_routes = '/api/agent/chat,/api/mcp/catalog-invoke,/api/cms/*,/dashboard/*,/mcp,/mcp/sse,/terminal,/games,/globe,/health',
  notes = 'Canonical platform master context — refreshed 637 (2026-06-14). Single SSOT row for inneranimalmedia repo/worker. Replaces stale ctx_iam_worker (deleted).',
  updated_at = unixepoch()
WHERE id = 'ctx_inneranimalmedia';
