-- 638: ctx_inneranimalmedia — GitHub, MCP deploy, deep docs, RAG retrieval pointers.
-- Apply:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business \
--     --remote -c wrangler.production.toml --file=./migrations/638_ctx_inneranimalmedia_rag_pointers.sql

UPDATE agentsam_project_context
SET
  description = 'Cloudflare Worker `inneranimalmedia` (inneranimalmedia.com). GitHub: https://github.com/SamPrimeaux/inneranimalmedia (main, branch main). MCP repo: https://github.com/SamPrimeaux/inneranimalmedia-mcp-server — deploy `cd /Users/samprimeaux/inneranimalmedia-mcp-server && npm run deploy:full`. Modular entry `src/index.js` (~626 modules) — legacy `worker.js` removed; all `/api` routes dispatch via `src/core/production-dispatch.js`. Core stack: Workers + D1 `inneranimalmedia-business` (cf87b717-d4e2-4cf8-bab0-a81268e32d49) + R2 (`inneranimalmedia`, `inneranimalmedia-autorag`, `artifacts`) + KV (`KV`, `SESSION_CACHE`) + Hyperdrive Supabase pgvector (dpmuvynqixblxsilnlut, agentsam schema) + Vectorize (6 indexes: memory/codebase/schema/documents/courses @1536 OpenAI + moviemode-gemini2-1536). Durable Objects: IAMCollaborationSession, AgentChatSqlV1, AgentBrowserLiveV1, ChessRoom, MyContainer. Services: MOVIEMODE_SERVICE, PTY_SERVICE (iam-vpc). Dashboard: React/Vite SPA `dashboard/` → R2 `static/dashboard/app/`. Main deploy: `npm run deploy:full` from repo root. Agent Sam chat spine: POST /api/agent/chat → agent-chat-spine.js → runtime-profile.js → resolveModelForTask (Thompson, 277 active arms on ws_inneranimalmedia). In-app tools: dispatchByToolCode → catalog-tool-executor.js — never proxy dashboard agent through MCP worker. Runtime lanes: MCP (mcp.inneranimalmedia.com), PTY/VPC (PTY_SERVICE), cloudflared tunnel, MyContainer sandbox. Per-site CMS rows: ctx_cms_* (priority 75). Client workers live on separate workspaces/repos with own agentsam_project_context rows. Auth: tenant_sam_primeaux, ws_inneranimalmedia, user au_871d920d1233cbd1. Deep docs: README.md + docs/platform/iam-runtime-architecture-2026-06.md. Vector retrieval: docs_knowledge_search → platform/inneranimalmedia/* chunks in agentsam_documents_oai3large_1536 (ingest: npm run run:ingest_platform_snapshot).',
  notes = 'Canonical platform SSOT (638). D1 row id=ctx_inneranimalmedia = fast compass. Deep runtime = semantic search docs_knowledge_search query "IAM platform snapshot" OR source_ref platform/inneranimalmedia/iam-platform-snapshot#*. Re-ingest after platform changes: npm run run:ingest_platform_snapshot. Manifest: docs/platform/iam-platform-docs.manifest.json.',
  updated_at = unixepoch()
WHERE id = 'ctx_inneranimalmedia';
