-- IAM Commerce Light + Inverted — Fuel-inspired admin chrome (light canvas, dark top bar, light sidebar).
-- Apply prod:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./migrations/675_iam_commerce_cms_themes.sql

INSERT OR REPLACE INTO cms_themes (
  id,
  tenant_id,
  name,
  slug,
  config,
  theme_family,
  sort_order,
  monaco_theme,
  monaco_bg,
  monaco_theme_data,
  tokens_json,
  css_vars_json,
  brand_json,
  layout_json,
  typography_json,
  components_json,
  motion_json,
  status,
  visibility,
  is_system,
  updated_at
) VALUES (
  'theme-iam-commerce-light',
  NULL,
  'IAM Commerce Light',
  'iam-commerce-light',
  '{"bg":"#F4F4F5","surface":"#FFFFFF","nav":"#202223","text":"#202223","textSecondary":"#616161","border":"#E1E3E5","primary":"#C8893A","primaryHover":"#A66E28","radius":"10px","monaco_bg":"#F6F6F7","is_dark":false,"cssVars":{"--bg-canvas":"#F4F4F5","--bg-app":"#F4F4F5","--bg-panel":"#FFFFFF","--bg-elevated":"#FAFAFA","--bg-shell":"#FFFFFF","--bg-nav":"#202223","--bg-hover":"rgba(32,34,35,0.06)","--text-primary":"#202223","--text-main":"#202223","--text-muted":"#616161","--text-nav":"#F4F4F5","--text-nav-muted":"#B5B5B5","--color-primary":"#C8893A","--accent-hover":"#A66E28","--border":"#E1E3E5","--border-subtle":"#E1E3E5","--editor-bg":"#F6F6F7","--editor-panel":"#FFFFFF","--editor-gutter":"#EBEBEB","--editor-border":"#E1E3E5","--editor-text":"#202223","--editor-muted":"#616161","--editor-accent":"#C8893A"}}',
  'light',
  5,
  'iam-commerce-light-monaco',
  '#F6F6F7',
  '{"base":"vs","inherit":true,"rules":[],"colors":{"editor.background":"#F6F6F7","editor.foreground":"#202223","editorLineNumber.foreground":"#9CA3AF","focusBorder":"#C8893A"}}',
  '{"palette":{"canvas":"#F4F4F5","panel":"#FFFFFF","panelAlt":"#FAFAFA","shell":"#FFFFFF","nav":"#202223","accent":"#C8893A","accentSoft":"#A66E28"},"preview":{"label":"Commerce Light","base":"#F4F4F5","monaco":"#F6F6F7","topbar":"#202223","sidebar":"#FFFFFF"}}',
  '{"--bg-shell":"#FFFFFF","--bg-nav":"#202223","--text-nav":"#F4F4F5","--editor-bg":"#F6F6F7"}',
  '{"style":"commerce","reference":"fuelnfreetime-admin"}',
  '{}',
  '{}',
  '{}',
  '{}',
  'active',
  'public',
  0,
  unixepoch()
);

INSERT OR REPLACE INTO cms_themes (
  id,
  tenant_id,
  name,
  slug,
  config,
  theme_family,
  sort_order,
  monaco_theme,
  monaco_bg,
  monaco_theme_data,
  tokens_json,
  css_vars_json,
  brand_json,
  layout_json,
  typography_json,
  components_json,
  motion_json,
  status,
  visibility,
  is_system,
  updated_at
) VALUES (
  'theme-iam-commerce-inverted',
  NULL,
  'IAM Commerce Inverted',
  'iam-commerce-inverted',
  '{"bg":"#141414","surface":"#1E1E1E","nav":"#FFFFFF","text":"#F4F4F5","textSecondary":"#A1A1AA","border":"#2E2E32","primary":"#C8893A","primaryHover":"#E0A04E","radius":"10px","monaco_bg":"#1A1A1A","is_dark":true,"cssVars":{"--bg-canvas":"#141414","--bg-app":"#141414","--bg-panel":"#1E1E1E","--bg-elevated":"#242424","--bg-shell":"#0A0A0A","--bg-nav":"#FFFFFF","--bg-hover":"rgba(255,255,255,0.06)","--text-primary":"#F4F4F5","--text-main":"#F4F4F5","--text-muted":"#A1A1AA","--text-nav":"#202223","--text-nav-muted":"#616161","--color-primary":"#C8893A","--accent-hover":"#E0A04E","--border":"#2E2E32","--border-subtle":"#2E2E32","--editor-bg":"#1A1A1A","--editor-panel":"#242424","--editor-gutter":"#141414","--editor-border":"#2E2E32","--editor-text":"#F4F4F5","--editor-muted":"#A1A1AA","--editor-accent":"#C8893A"}}',
  'dark',
  6,
  'iam-commerce-inverted-monaco',
  '#1A1A1A',
  '{"base":"vs-dark","inherit":true,"rules":[],"colors":{"editor.background":"#1A1A1A","editor.foreground":"#F4F4F5","editorLineNumber.foreground":"#71717A","focusBorder":"#C8893A"}}',
  '{"palette":{"canvas":"#141414","panel":"#1E1E1E","panelAlt":"#242424","shell":"#0A0A0A","nav":"#FFFFFF","accent":"#C8893A","accentSoft":"#E0A04E"},"preview":{"label":"Commerce Inverted","base":"#141414","monaco":"#1A1A1A","topbar":"#FFFFFF","sidebar":"#0A0A0A"}}',
  '{"--bg-shell":"#0A0A0A","--bg-nav":"#FFFFFF","--text-nav":"#202223","--editor-bg":"#1A1A1A"}',
  '{"style":"commerce-inverted","reference":"fuelnfreetime-admin-inverted"}',
  '{}',
  '{}',
  '{}',
  '{}',
  'active',
  'public',
  0,
  unixepoch()
);
