-- 680: Refresh canonical platform master context (ctx_inneranimalmedia) — June 2026 milestone.
-- Operator lane parity (679), ExecOS GCP fabric, Design Studio CAD on GCP, vector compact manifest.
-- Verified against repo + remote D1: 2026-06-22.
-- Apply:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business \
--     --remote -c wrangler.production.toml --file=./migrations/680_ctx_inneranimalmedia_milestone_refresh.sql

UPDATE agentsam_project_context
SET
  project_name = 'inneranimalmedia Worker — Platform Master',
  project_type = 'saas-platform',
  status = 'active',
  priority = 100,
  description = 'Cloudflare Worker `inneranimalmedia` (inneranimalmedia.com). GitHub: https://github.com/SamPrimeaux/inneranimalmedia (main). MCP repo: https://github.com/SamPrimeaux/inneranimalmedia-mcp-server — deploy `cd inneranimalmedia-mcp-server && npm run deploy:full`. Modular entry `src/index.js` (~626 modules); all `/api` routes via `src/core/production-dispatch.js`. Core stack: Workers + D1 `inneranimalmedia-business` (cf87b717-d4e2-4cf8-bab0-a81268e32d49) + R2 (`inneranimalmedia`, `inneranimalmedia-autorag`, `artifacts`) + KV (`KV`, `SESSION_CACHE`) + Hyperdrive Supabase pgvector (dpmuvynqixblxsilnlut, agentsam schema) + Vectorize (memory/codebase/schema/documents/courses @1536 + moviemode-gemini2-1536). Durable Objects: IAMCollaborationSession, AgentChatSqlV1, AgentBrowserLiveV1, ChessRoom, MyContainer. Services: MOVIEMODE_SERVICE, PTY_SERVICE (iam-vpc), EXECOS (Worker binding → execos.inneranimalmedia.com). ExecOS GCP chain (PATH C): CORE/MCP → EXECOS binding → POST /run → terminal.inneranimalmedia.com/run → GCP iam-tunnel `~/ExecOS` pm2 :3099. EXECOS_KEY SSOT: `.env.cloudflare`; sync `scripts/sync-execos-key.sh`; smoke `scripts/test/smoke-execos-chain.sh`. Operator lanes (679): five emails share person_uuid 550e8400-e29b-41d4-a716-446655440001, platform_operator=1, ws_inneranimalmedia, cwd_strategy=host_default, GCP repo `/home/samprimeaux/inneranimalmedia` — info@inneranimals.com (au_871d920d1233cbd1 canonical), sam@inneranimalmedia.com, meauxbility@gmail.com, ceosamprimeaux@gmail.com, inneranimalclothing@gmail.com. Tenant isolation: Connor (au_5d17673408aaebc7) platform_operator=0, cwd_strategy=platform_workspace, ws_connor_mcneely + ws_fuelnfreetime only — no Sam .env or operator exec. Dashboard: React/Vite SPA `dashboard/` → R2 `static/dashboard/app/`. Agent Sam: POST /api/agent/chat → agent-chat-spine → resolveModelForTask → dispatchByToolCode (never proxy dashboard through MCP worker). Per-site CMS: ctx_cms_* (priority 75). Client workers (companionscpas etc.) separate repos/workspaces — never patch from IAM platform context.',
  goals = 'Runtime spine: agent-chat-spine → resolveRuntimeProfile → resolveModelForTask → agent-tool-loop with dispatchByToolCode. Operator lane parity (679): five Sam emails → identical ws_inneranimalmedia plane, host_default, 29 workspaces, MCP surfaces (chatgpt/claude/cursor). ExecOS fabric (1C shipped): execos-fabric.js + cad-pty-executor.js dispatch CAD/PTY to GCP; resolveCadExecRepoRoot operators → host_default. Design Studio: blueprint → POST /api/cad/openscad/generate → agentsam_cad_jobs → POST /api/cad/jobs/:id/execute → GLB R2 → VoxelEngine viewport. CMS M3: per-site ctx_cms_* + cms_pages/sections/themes/live-editor. Code indexer: agentsam_code_index_job → code-indexer.js → Supabase agentsam_codebase_chunks → AGENTSAM_VECTORIZE_CODE. Vector compact milestone: docs/platform/platform-milestone-2026-06.manifest.json → `scripts/compact_platform_milestone_vector.sh` (docs + memory routers + ExecOS/CAD code paths + deep_archive 3072). Context compaction: conversation-compaction.js + r2-context-store.js digests. Agent.js decomposition ongoing (classify-intent.js extracted). Meet engine MEET_ENGINE=realtimekit. Client ops: separate worker repos.',
  constraints = 'NO emojis — platform-wide. NEVER hardcode model IDs, tenant IDs, workspace IDs, or API keys in source — resolve from D1/session at runtime. Deploy ONLY via `npm run deploy:full` from repo root — never `npm run deploy` alone for full product ship; never wrangler deploy without frontend R2 sync when dashboard changed. D1 wrangler: always `--remote -c wrangler.production.toml`. Two repos — NEVER mix deploy paths: main app inneranimalmedia, MCP inneranimalmedia-mcp-server. In-app Agent Sam uses dispatchByToolCode on main worker — NEVER route dashboard chat through mcp.inneranimalmedia.com. New `/api` routes: add ONLY in production-dispatch.js. EXECOS_KEY: rotate/sync via `scripts/sync-execos-key.sh` across CORE Worker, execos dispatcher, MCP server, GCP VM; never commit secrets. Operator exec cwd on GCP is `/home/samprimeaux/inneranimalmedia` — tenants (Connor etc.) use platform_workspace under `/workspace/{tenant_id}/{user_id}` — never Sam operator .env. Patches over rewrites; backup before editing. DB writes non-fatal (try/catch, ctx.waitUntil). agentsam_tools is sole tool catalog SSOT. Superadmin bypass: user.role === superadmin.',
  current_blockers = 'DesignStudioPage.tsx subscribeRunEvents SSE not wired (poll fallback works). Agent mode can compile zero tools while still calling model. list_dir/write_file loopback to unwired /api/fs/list and /api/fs/write. agent.js still monolithic (~4742 lines). Dashboard subset-shared.chunk.js ~737KB gzip (target <200KB). Multitask can report ok with empty subagent output. MCP ExecOS legacy bridge fallback still gated (execos_bridge_fallback_enabled) — full removal after 7d green. Open security audit items outstanding. Client worker changes belong in client repos — not IAM platform patches.',
  primary_tables = 'agentsam_agent_run,agentsam_chat_sessions,agentsam_workspace,agentsam_workspace_state,agentsam_tools,agentsam_routing_arms,agentsam_model_catalog,agentsam_prompt_routes,agentsam_route_requirements,agentsam_project_context,agentsam_code_index_job,agentsam_context_digest,agentsam_compaction_events,agentsam_usage_rollups_daily,agentsam_tool_call_log,agentsam_workflow_runs,agentsam_cad_jobs,designstudio_design_blueprints,cms_pages,cms_page_sections,cms_themes',
  secondary_tables = 'agentsam_workspace_recent,agentsam_subagents,agentsam_memory,agentsam_skill,agentsam_routing_policy,agentsam_routing_audit,agentsam_tenant_credentials,agentsam_cron_runs,agentsam_user_policy,agentsam_mcp_audit,finance_transactions,deployments,agentsam_mcp_oauth_tool_allowlist,user_api_keys,user_secrets,scene_snapshots,cms_assets',
  workers_involved = 'inneranimalmedia,inneranimalmedia-mcp-server,moviemode-service,execos',
  r2_buckets_involved = 'inneranimalmedia,inneranimalmedia-autorag,artifacts',
  domains_involved = 'inneranimalmedia.com,mcp.inneranimalmedia.com,execos.inneranimalmedia.com,terminal.inneranimalmedia.com,webhooks.inneranimalmedia.com,artifacts.inneranimalmedia.com,inneranimals.com,meauxbility.org',
  mcp_services_involved = 'agentsam_github_read,agentsam_github_write,agentsam_github_pr,agentsam_github_issue,agentsam_d1_query,agentsam_d1_write,agentsam_d1_migrate,agentsam_r2_get,agentsam_r2_put,agentsam_r2_list,agentsam_r2_delete,agentsam_supabase_query,agentsam_supabase_write,agentsam_supabase_vector,agentsam_cf_vectorize,agentsam_memory_manager,agentsam_terminal_local,agentsam_terminal_remote,agentsam_terminal_sandbox,agentsam_send_email,agentsam_stack_deploy,agentsam_container_exec,agentsam_mcp_audit',
  key_files = 'src/index.js,src/core/production-dispatch.js,src/core/runtime-profile.js,src/core/resolveModel.js,src/core/agent-tool-loop.js,src/core/dispatch-by-tool-code.js,src/core/catalog-tool-executor.js,src/core/execos-fabric.js,src/core/cad-pty-executor.js,src/core/platform-operator-policy.js,src/api/agent-chat-spine.js,src/api/agent.js,src/api/cad.js,src/api/designstudio/,src/core/code-indexer.js,src/core/collab-broadcast.js,src/core/r2-context-store.js,dashboard/src/pages/DesignStudioPage.tsx,scripts/sync-execos-key.sh,scripts/compact_platform_milestone_vector.sh,scripts/test/smoke-execos-chain.sh,docs/platform/platform-milestone-2026-06.manifest.json,wrangler.production.toml,migrations/',
  related_routes = '/api/agent/chat,/api/mcp/catalog-invoke,/api/cms/*,/api/cad/*,/dashboard/designstudio,/dashboard/*,/mcp,/mcp/sse,/terminal,/games,/globe,/health',
  notes = 'Canonical platform SSOT — refreshed 680 (2026-06-22). D1 row id=ctx_inneranimalmedia = fast compass. Memory routers (pinned): iam_platform_context_router_v1, designstudio_sprint_router_v1, agentic_edge_sprint_router_v1, byok_sprint_router_v1. Deep retrieval: docs_knowledge_search platform/inneranimalmedia/* OR source_ref in agentsam_documents_oai3large_1536 + AGENTSAM_VECTORIZE_DOCUMENTS. Milestone manifest: docs/platform/platform-milestone-2026-06.manifest.json. Vector compact: ./scripts/compact_platform_milestone_vector.sh or npm run run:compact_platform_milestone_vector. Operator lanes: migration 679. EXECOS_KEY sync: scripts/sync-execos-key.sh. Exec smoke: scripts/test/smoke-execos-chain.sh. Platform snapshot re-ingest: npm run run:ingest_platform_snapshot.',
  updated_at = unixepoch()
WHERE id = 'ctx_inneranimalmedia';
