-- 681: Refresh Design Studio CAD + /games remaster context (ctx_designstudio_games_remaster_2026_06).
-- ExecOS GCP CAD dispatch, CadToolDock shipped, London Dream Railway playable, games 3D chess Phases A-D open.
-- Verified against repo + remote D1: 2026-06-22.
-- Apply:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business \
--     --remote -c wrangler.production.toml --file=./migrations/681_ctx_designstudio_games_remaster_refresh.sql

UPDATE agentsam_project_context
SET
  project_name = 'Design Studio CAD Remaster + 3D Chess /games Upgrade',
  project_type = 'feature-sprint',
  status = 'active',
  priority = 75,
  description = 'Design Studio CAD remaster shipped on /dashboard/designstudio: CadToolDock (Blueprints, Generate, Jobs, Scene, Assets, Creation Station), useDesignStudioCad + useCadJobPoll hooks, cad_glb_ready collab spawn, MEAUX_CAD chat context. CAD execute path now dispatches via ExecOS GCP (src/core/cad-pty-executor.js → execos-fabric.js → terminal.inneranimalmedia.com/run → iam-tunnel pm2 :3099) — operators use host_default repo /home/samprimeaux/inneranimalmedia; iPhone users never run OpenSCAD locally. Public /games upgraded from 2D Unicode chess to 3D GLB ChessViewport (board_main.glb + 12 piece GLBs, games-room.js, static/pages/games/room.html); London Dream Railway playable section live (migration 677). /dashboard/designstudio is the single buildout surface for CAD + games creations; /games is public-facing (no /dashboard/meauxgames — Phase E cancelled). Memory router: agentsam_memory.key=designstudio_sprint_router_v1. Deep docs: docs/platform/designstudio-sprint-plan.md, docs/inneranimalmedia/product/designstudio/E2E-COMPLETE-PLAN-2026-06.md, docs/platform/games-3d-chess-sprint-plan.md.',
  goals = '["CAD E2E on GCP ExecOS: blueprint → POST /api/cad/openscad/generate → agentsam_cad_jobs → POST /api/cad/jobs/:id/execute → cad-pty-executor → GLB R2 → VoxelEngine spawn (smoke: scripts/test/smoke-execos-chain.sh)","Wire DesignStudioPage subscribeRunEvents SSE (useDesignStudioCad exposes hook; poll fallback works today)","Agent Sam cadcreator tools E2E without manual toolbar (todo_ds_sprint_runner_proof, todo_ds_sprint_ship)","Games Phase A: guest-safe /api/games/* auth — lobby works logged-in, guests may 401 on WS","Games Phase B: server-side move validation in ChessRoom DO","Games Phase C: polish — square highlights, move animation, mobile, stale room cleanup","Games Phase D: unify Design Studio and public room via ?room= param","Fix chess pieces not spawning in /games room view (todo_games3d_pieces_not_spawning)","Morning smoke: 2 browsers same room → 3D board + e2-e4 sync both clients"]',
  constraints = '["OpenSCAD and Blender run on operator GCP ExecOS host — never in Worker isolate","EXECOS_KEY synced via scripts/sync-execos-key.sh across CORE, execos, MCP, GCP VM before CAD exec","/dashboard/designstudio is sole CAD/games buildout — /dashboard/meauxgames will NOT be built (Phase E cancelled)","Frontend project_type enum still uses MEAAUX_GAMES (double-A typo) for chess scenes — matches live data, normalization deferred","Design Studio CAD scenes use project_type MEAUX_CAD (single-A, confirmed live in UI header)","Tenant CAD exec uses platform_workspace /workspace/{tenant}/{user} — never Sam operator .env"]',
  current_blockers = '["Chess pieces do not spawn in /games room view (todo_games3d_pieces_not_spawning open) — blocks meaningful Phase B/C smoke","DesignStudioPage.tsx does not call subscribeRunEvents — SSE proxy exists, poll fallback only","Guest auth on /api/games/* WS not guest-safe — may 401 for non-logged-in players (Phase A)","No server-side move validation in ChessRoom DO — illegal moves accepted (Phase B)","Agent CAD runner proof + iPhone ship criteria still open (todo_ds_sprint_runner_proof, todo_ds_sprint_ship)","Two-browser e2-e4 multiplayer smoke not yet verified"]',
  primary_tables = 'agentsam_cad_jobs,designstudio_design_blueprints,scene_snapshots,cms_assets,games,game_rooms,cms_page_sections',
  secondary_tables = 'agentsam_todo,agentsam_memory,agentsam_workflow_runs,agentsam_pgvector_lane_registry',
  workers_involved = 'inneranimalmedia,inneranimalmedia-mcp-server,execos',
  r2_buckets_involved = 'inneranimalmedia,artifacts',
  domains_involved = 'inneranimalmedia.com,terminal.inneranimalmedia.com,execos.inneranimalmedia.com',
  key_files = 'dashboard/components/DesignStudioPage.tsx,dashboard/components/designstudio/DesignStudioLeftPanel.tsx,dashboard/components/designstudio/CadToolDock.tsx,dashboard/components/designstudio/hooks/useDesignStudioCad.ts,dashboard/components/designstudio/hooks/useCadJobPoll.ts,dashboard/components/designstudio/creation-station/DesignStudioCreationStation.tsx,dashboard/lib/ChessViewport.ts,dashboard/entries/games-room.tsx,dashboard/games-room.js,static/pages/games/room.html,src/api/designstudio/,src/api/cad.js,src/core/cad-pty-executor.js,src/core/execos-fabric.js,src/core/cad-job-complete.js,src/do/Legacy.js,scripts/designstudio/cad-job-runner.mjs,scripts/test/smoke-execos-chain.sh,docs/platform/designstudio-sprint-plan.md,docs/platform/games-3d-chess-sprint-plan.md',
  related_routes = '/dashboard/designstudio,/games,/games/room_*,/api/cad/*,/api/designstudio/*,/api/designstudio/blueprints,/api/designstudio/scenes,/api/designstudio/runs/:id/events,/api/games/*',
  linked_todo_ids = '["todo_ds_sprint_runner_proof","todo_ds_sprint_ship","todo_games3d_morning_smoke","todo_games3d_phaseA_guest_auth","todo_games3d_phaseB_move_validation","todo_games3d_phaseC_polish","todo_games3d_phaseD_unify_rooms","todo_games3d_pieces_not_spawning"]',
  notes = 'Refreshed 681 (2026-06-22). Parent compass: ctx_inneranimalmedia. Memory router: designstudio_sprint_router_v1. Re-ingest: npm run run:ingest_designstudio_sprint_plan. Vector compact: docs/platform/platform-milestone-2026-06.manifest.json. CAD exec: GCP ExecOS via cad-pty-executor (replaces Mac-only runner for operators). Games: 3D chess shipped 2026-06-14; London Dream Railway playable 677. /dashboard/meauxgames cancelled — designstudio is single surface. Morning smoke pending pieces fix.',
  updated_at = unixepoch()
WHERE id = 'ctx_designstudio_games_remaster_2026_06';
