-- 824: Sonnet 5 bare API id + chat_intent keyword seed (phase1)
-- Apply:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./migrations/824_sonnet5_unpin_chat_intent_keywords.sql

-- prop-sonnet5-api-id-unpinned (idempotent)
UPDATE agentsam_model_catalog SET
  anthropic_model_id = 'claude-sonnet-5',
  updated_at = unixepoch()
WHERE model_key = 'claude-sonnet-5'
  AND COALESCE(anthropic_model_id, '') != 'claude-sonnet-5';

-- chat_intent_* patterns (phase1) — tune via D1 without deploy
INSERT OR IGNORE INTO agentsam_classification_keywords (id, purpose, pattern, label, active, notes) VALUES
('ck_ci_wf_1', 'chat_intent_workflow_orchestration', 'run workflow', 'agent', 1, NULL),
('ck_ci_wf_2', 'chat_intent_workflow_orchestration', 'start workflow', 'agent', 1, NULL),
('ck_ci_wf_3', 'chat_intent_workflow_orchestration', 'trigger workflow', 'agent', 1, NULL),
('ck_ci_wf_4', 'chat_intent_workflow_orchestration', 'execute workflow', 'agent', 1, NULL),
('ck_ci_wf_5', 'chat_intent_workflow_orchestration', 'agentic run', 'agent', 1, NULL),
('ck_ci_dep_1', 'chat_intent_deploy', 'deploy', 'agent', 1, NULL),
('ck_ci_dep_2', 'chat_intent_deploy', 'wrangler deploy', 'agent', 1, NULL),
('ck_ci_dep_3', 'chat_intent_deploy', 'npm run deploy', 'agent', 1, NULL),
('ck_ci_dep_4', 'chat_intent_deploy', 'push to prod', 'agent', 1, NULL),
('ck_ci_dep_5', 'chat_intent_deploy', 'promote', 'agent', 1, NULL),
('ck_ci_dep_6', 'chat_intent_deploy', 'cloudflare build', 'agent', 1, NULL),
('ck_ci_mt_1', 'chat_intent_multitask', 'orchestrate', 'agent', 1, NULL),
('ck_ci_mt_2', 'chat_intent_multitask', 'multi-step', 'agent', 1, NULL),
('ck_ci_mt_3', 'chat_intent_multitask', 'multi-agent', 'agent', 1, NULL),
('ck_ci_mt_4', 'chat_intent_multitask', 'end-to-end', 'agent', 1, NULL),
('ck_ci_mt_5', 'chat_intent_multitask', 'build-and-deploy', 'agent', 1, NULL),
('ck_ci_sp_1', 'chat_intent_agent_spawn', 'spawn subagent', 'agent', 1, NULL),
('ck_ci_sp_2', 'chat_intent_agent_spawn', 'delegate to', 'agent', 1, NULL),
('ck_ci_sp_3', 'chat_intent_agent_spawn', 'subagent', 'agent', 1, NULL),
('ck_ci_dw_1', 'chat_intent_d1_write', 'insert into', 'agent', 1, NULL),
('ck_ci_dw_2', 'chat_intent_d1_write', 'd1 write', 'agent', 1, NULL),
('ck_ci_dw_3', 'chat_intent_d1_write', 'bulk insert', 'agent', 1, NULL),
('ck_ci_dw_4', 'chat_intent_d1_write', 'populate table', 'agent', 1, NULL),
('ck_ci_dw_5', 'chat_intent_d1_write', 'store in d1', 'agent', 1, NULL),
('ck_ci_dq_1', 'chat_intent_d1_query', 'd1_query', 'agent', 1, NULL),
('ck_ci_dq_2', 'chat_intent_d1_query', 'what tables', 'agent', 1, NULL),
('ck_ci_dq_3', 'chat_intent_d1_query', 'which tables', 'agent', 1, NULL),
('ck_ci_r2_1', 'chat_intent_r2_ops', 'r2 bucket', 'agent', 1, NULL),
('ck_ci_r2_2', 'chat_intent_r2_ops', 'list r2', 'agent', 1, NULL),
('ck_ci_r2_3', 'chat_intent_r2_ops', 'upload to', 'agent', 1, NULL),
('ck_ci_cf_1', 'chat_intent_cf_ops', 'wrangler', 'agent', 1, NULL),
('ck_ci_cf_2', 'chat_intent_cf_ops', 'durable object', 'agent', 1, NULL),
('ck_ci_cf_3', 'chat_intent_cf_ops', 'kv namespace', 'agent', 1, NULL),
('ck_ci_cf_4', 'chat_intent_cf_ops', 'd1 migrate', 'agent', 1, NULL),
('ck_ci_sh_1', 'chat_intent_terminal_execution', 'run command', 'agent', 1, NULL),
('ck_ci_sh_2', 'chat_intent_terminal_execution', 'terminal', 'agent', 1, NULL),
('ck_ci_sh_3', 'chat_intent_terminal_execution', 'bash', 'agent', 1, NULL),
('ck_ci_ws_1', 'chat_intent_web_search', 'search the web', 'agent', 1, NULL),
('ck_ci_ws_2', 'chat_intent_web_search', 'web search', 'agent', 1, NULL),
('ck_ci_ws_3', 'chat_intent_web_search', 'look it up online', 'agent', 1, NULL),
('ck_ci_vz_1', 'chat_intent_vectorize', 'vectorize', 'agent', 1, NULL),
('ck_ci_vz_2', 'chat_intent_vectorize', 'semantic search', 'agent', 1, NULL),
('ck_ci_vz_3', 'chat_intent_vectorize', 'knowledge base', 'agent', 1, NULL),
('ck_ci_gh_1', 'chat_intent_github', 'github', 'agent', 1, NULL),
('ck_ci_gh_2', 'chat_intent_github', 'pull request', 'agent', 1, NULL),
('ck_ci_gh_3', 'chat_intent_github', 'git push', 'agent', 1, NULL),
('ck_ci_sql_1', 'chat_intent_sql_d1_generation', 'create table', 'agent', 1, NULL),
('ck_ci_sql_2', 'chat_intent_sql_d1_generation', 'alter table', 'agent', 1, NULL),
('ck_ci_dbg_1', 'chat_intent_debug', 'debug', 'agent', 1, NULL),
('ck_ci_dbg_2', 'chat_intent_debug', 'not working', 'agent', 1, NULL),
('ck_ci_dbg_3', 'chat_intent_debug', 'stack trace', 'agent', 1, NULL),
('ck_ci_dbg_4', 'chat_intent_debug', 'diagnose', 'agent', 1, NULL),
('ck_ci_sc_1', 'chat_intent_search_code', 'grep', 'agent', 1, NULL),
('ck_ci_sc_2', 'chat_intent_search_code', 'find in codebase', 'agent', 1, NULL),
('ck_ci_sc_3', 'chat_intent_search_code', 'where is', 'agent', 1, NULL),
('ck_ci_sc_4', 'chat_intent_search_code', 'find where', 'agent', 1, NULL),
('ck_ci_sc_5', 'chat_intent_search_code', 'is defined', 'agent', 1, NULL),
('ck_ci_sc_6', 'chat_intent_search_code', 'search codebase', 'agent', 1, NULL),
('ck_ci_sc_7', 'chat_intent_search_code', 'locate file', 'agent', 1, NULL),
('ck_ci_rf_1', 'chat_intent_refactor', 'refactor', 'agent', 1, NULL),
('ck_ci_rf_2', 'chat_intent_refactor', 'extract function', 'agent', 1, NULL),
('ck_ci_rv_1', 'chat_intent_review', 'code review', 'agent', 1, NULL),
('ck_ci_rv_2', 'chat_intent_review', 'audit', 'agent', 1, NULL),
('ck_ci_cd_1', 'chat_intent_code', 'implement', 'agent', 1, NULL),
('ck_ci_cd_2', 'chat_intent_code', 'edit file', 'agent', 1, NULL),
('ck_ci_cd_3', 'chat_intent_code', 'fix file', 'agent', 1, NULL),
('ck_ci_cd_4', 'chat_intent_code', 'create file', 'agent', 1, NULL),
('ck_ci_cd_5', 'chat_intent_code', 'worker.js', 'agent', 1, NULL),
('ck_ci_cd_6', 'chat_intent_code', '.tsx', 'agent', 1, NULL),
('ck_ci_cd_7', 'chat_intent_code', '.jsx', 'agent', 1, NULL),
('ck_ci_pl_1', 'chat_intent_plan', 'roadmap', 'agent', 1, NULL),
('ck_ci_pl_2', 'chat_intent_plan', 'architect', 'agent', 1, NULL),
('ck_ci_pl_3', 'chat_intent_plan', 'wireframe', 'agent', 1, NULL),
('ck_ci_pl_4', 'chat_intent_plan', 'task breakdown', 'agent', 1, NULL),
('ck_ci_br_1', 'chat_intent_browser', 'screenshot', 'agent', 1, NULL),
('ck_ci_br_2', 'chat_intent_browser', 'playwright', 'agent', 1, NULL),
('ck_ci_br_3', 'chat_intent_browser', 'puppeteer', 'agent', 1, NULL),
('ck_ci_br_4', 'chat_intent_browser', 'open the browser', 'agent', 1, NULL),
('ck_ci_br_5', 'chat_intent_browser', 'navigate to', 'agent', 1, NULL),
('ck_ci_br_6', 'chat_intent_browser', 'dom inspect', 'agent', 1, NULL),
('ck_ci_sk_1', 'chat_intent_skill_use', 'use skill', 'agent', 1, NULL),
('ck_ci_sk_2', 'chat_intent_skill_use', 'run skill', 'agent', 1, NULL),
('ck_ci_tu_1', 'chat_intent_tool_use', 'use tool', 'agent', 1, NULL),
('ck_ci_tu_2', 'chat_intent_tool_use', 'mcp tool', 'agent', 1, NULL),
('ck_ci_cms_1', 'chat_intent_cms_edit', 'cms page', 'agent', 1, NULL),
('ck_ci_cms_2', 'chat_intent_cms_edit', 'shopify', 'agent', 1, NULL),
('ck_ci_rc_1', 'chat_intent_recall', 'recall', 'auto', 1, NULL),
('ck_ci_rc_2', 'chat_intent_recall', 'remind me', 'auto', 1, NULL),
('ck_ci_ex_1', 'chat_intent_explain', 'explain', 'auto', 1, NULL),
('ck_ci_ex_2', 'chat_intent_explain', 'how does', 'auto', 1, NULL),
('ck_ci_ex_3', 'chat_intent_explain', 'eli5', 'auto', 1, NULL),
('ck_ci_esc_1', 'chat_intent_escalate', 'maybe', NULL, 1, 'phase2 soft cue'),
('ck_ci_esc_2', 'chat_intent_escalate', 'not sure', NULL, 1, 'phase2 soft cue'),
('ck_ci_esc_3', 'chat_intent_escalate', 'figure out', NULL, 1, 'phase2 soft cue'),
('ck_ci_esc_4', 'chat_intent_escalate', 'help me decide', NULL, 1, 'phase2 soft cue');
