-- 932: Capability-owned authorization schema and canonical taxonomy.

CREATE TABLE IF NOT EXISTS agentsam_capabilities (
  capability_key TEXT PRIMARY KEY,
  domain TEXT NOT NULL,
  verb TEXT NOT NULL,
  description TEXT NOT NULL,
  is_mutating INTEGER NOT NULL DEFAULT 0 CHECK (is_mutating IN (0, 1)),
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE TABLE IF NOT EXISTS agentsam_tool_capabilities (
  tool_id TEXT NOT NULL REFERENCES agentsam_tools(id) ON DELETE CASCADE,
  capability_key TEXT NOT NULL REFERENCES agentsam_capabilities(capability_key),
  requirement_type TEXT NOT NULL DEFAULT 'required' CHECK (requirement_type = 'required'),
  is_primary INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1)),
  operations_json TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  UNIQUE (tool_id, capability_key)
);

CREATE INDEX IF NOT EXISTS idx_agentsam_tool_capabilities_tool
  ON agentsam_tool_capabilities(tool_id);
CREATE INDEX IF NOT EXISTS idx_agentsam_tool_capabilities_capability
  ON agentsam_tool_capabilities(capability_key);

INSERT OR REPLACE INTO agentsam_capabilities
  (capability_key, domain, verb, description, is_mutating, is_active, created_at, updated_at)
VALUES
  ('agent.read','agent','read','Read registered agent definitions.',0,1,unixepoch(),unixepoch()),
  ('agent.execute','agent','execute','Execute a registered agent.',1,1,unixepoch(),unixepoch()),
  ('agent.spawn','agent','spawn','Create or spawn an agent session.',1,1,unixepoch(),unixepoch()),
  ('workflow.read','workflow','read','Read workflow definitions and state.',0,1,unixepoch(),unixepoch()),
  ('workflow.execute','workflow','execute','Execute a workflow.',1,1,unixepoch(),unixepoch()),
  ('workflow.manage','workflow','manage','Create or mutate workflow definitions.',1,1,unixepoch(),unixepoch()),
  ('ticket.read','ticket','read','Read tickets and notes.',0,1,unixepoch(),unixepoch()),
  ('ticket.write','ticket','write','Create tickets or notes.',1,1,unixepoch(),unixepoch()),
  ('ticket.status','ticket','status','Change ticket lifecycle state.',1,1,unixepoch(),unixepoch()),
  ('memory.read','memory','read','Search, list, or read scoped memory.',0,1,unixepoch(),unixepoch()),
  ('memory.write','memory','write','Create or update scoped memory.',1,1,unixepoch(),unixepoch()),
  ('memory.delete','memory','delete','Delete or resolve scoped memory.',1,1,unixepoch(),unixepoch()),
  ('file.read','file','read','Read workspace files.',0,1,unixepoch(),unixepoch()),
  ('file.search','file','search','Search workspace files.',0,1,unixepoch(),unixepoch()),
  ('file.write','file','write','Create or mutate workspace files.',1,1,unixepoch(),unixepoch()),
  ('git.read','git','read','Read Git status, diff, and history.',0,1,unixepoch(),unixepoch()),
  ('git.commit','git','commit','Create a Git commit.',1,1,unixepoch(),unixepoch()),
  ('git.push','git','push','Push Git refs to a remote.',1,1,unixepoch(),unixepoch()),
  ('github.read','github','read','Read GitHub resources.',0,1,unixepoch(),unixepoch()),
  ('github.write','github','write','Mutate GitHub resources.',1,1,unixepoch(),unixepoch()),
  ('github.admin','github','admin','Administer GitHub repositories or organizations.',1,1,unixepoch(),unixepoch()),
  ('github.security.read','github.security','read','Read GitHub security findings.',0,1,unixepoch(),unixepoch()),
  ('github.workflow.execute','github.workflow','execute','Trigger GitHub Actions workflows.',1,1,unixepoch(),unixepoch()),
  ('terminal.execute','terminal','execute','Execute a workspace terminal command.',1,1,unixepoch(),unixepoch()),
  ('container.execute','container','execute','Execute a command in an isolated container.',1,1,unixepoch(),unixepoch()),
  ('python.execute','python','execute','Execute Python code.',1,1,unixepoch(),unixepoch()),
  ('d1.read','d1','read','Read Cloudflare D1 data or schema.',0,1,unixepoch(),unixepoch()),
  ('d1.write','d1','write','Mutate Cloudflare D1 data.',1,1,unixepoch(),unixepoch()),
  ('d1.migrate','d1','migrate','Apply Cloudflare D1 schema migrations.',1,1,unixepoch(),unixepoch()),
  ('supabase.read','supabase','read','Read scoped Supabase/Postgres data.',0,1,unixepoch(),unixepoch()),
  ('supabase.write','supabase','write','Mutate scoped Supabase/Postgres data.',1,1,unixepoch(),unixepoch()),
  ('supabase.migrate','supabase','migrate','Apply Supabase/Postgres schema migrations.',1,1,unixepoch(),unixepoch()),
  ('supabase.vector.read','supabase.vector','read','Query Supabase vector data.',0,1,unixepoch(),unixepoch()),
  ('supabase.vector.write','supabase.vector','write','Mutate Supabase vector data.',1,1,unixepoch(),unixepoch()),
  ('kv.read','kv','read','Read Cloudflare KV.',0,1,unixepoch(),unixepoch()),
  ('kv.write','kv','write','Write Cloudflare KV.',1,1,unixepoch(),unixepoch()),
  ('kv.delete','kv','delete','Delete Cloudflare KV values.',1,1,unixepoch(),unixepoch()),
  ('r2.read','r2','read','List or read R2 objects.',0,1,unixepoch(),unixepoch()),
  ('r2.write','r2','write','Write R2 objects.',1,1,unixepoch(),unixepoch()),
  ('r2.delete','r2','delete','Delete R2 objects.',1,1,unixepoch(),unixepoch()),
  ('vector.read','vector','read','Query Vectorize indexes.',0,1,unixepoch(),unixepoch()),
  ('vector.write','vector','write','Mutate Vectorize indexes.',1,1,unixepoch(),unixepoch()),
  ('images.read','images','read','Read image assets and metadata.',0,1,unixepoch(),unixepoch()),
  ('images.write','images','write','Upload or mutate image assets.',1,1,unixepoch(),unixepoch()),
  ('cloudflare.read','cloudflare','read','Read Cloudflare resource metadata.',0,1,unixepoch(),unixepoch()),
  ('cloudflare.execute','cloudflare','execute','Execute a scoped Cloudflare operation.',1,1,unixepoch(),unixepoch()),
  ('cloudflare.deploy','cloudflare','deploy','Deploy a Cloudflare Worker or stack.',1,1,unixepoch(),unixepoch()),
  ('browser.read','browser','read','Inspect browser content.',0,1,unixepoch(),unixepoch()),
  ('browser.navigate','browser','navigate','Navigate a browser session.',1,1,unixepoch(),unixepoch()),
  ('browser.execute','browser','execute','Execute browser automation or script.',1,1,unixepoch(),unixepoch()),
  ('browser.capture','browser','capture','Capture a browser screenshot or snapshot.',0,1,unixepoch(),unixepoch()),
  ('web.search','web','search','Search the public web.',0,1,unixepoch(),unixepoch()),
  ('web.fetch','web','fetch','Fetch public web content.',0,1,unixepoch(),unixepoch()),
  ('email.read','email','read','Read mail and labels.',0,1,unixepoch(),unixepoch()),
  ('email.draft','email','draft','Create or mutate an email draft.',1,1,unixepoch(),unixepoch()),
  ('email.modify','email','modify','Modify mail state or labels.',1,1,unixepoch(),unixepoch()),
  ('email.send','email','send','Send email.',1,1,unixepoch(),unixepoch()),
  ('cms.read','cms','read','Read CMS content and state.',0,1,unixepoch(),unixepoch()),
  ('cms.write','cms','write','Mutate CMS drafts and content.',1,1,unixepoch(),unixepoch()),
  ('cms.publish','cms','publish','Publish CMS content.',1,1,unixepoch(),unixepoch()),
  ('media.generate','media','generate','Generate image, video, or 3D media.',1,1,unixepoch(),unixepoch()),
  ('media.transform','media','transform','Transform an existing media asset.',1,1,unixepoch(),unixepoch()),
  ('media.render','media','render','Render a media project.',1,1,unixepoch(),unixepoch()),
  ('media.export','media','export','Export a media project or asset.',1,1,unixepoch(),unixepoch()),
  ('media.status','media','status','Read media task status.',0,1,unixepoch(),unixepoch()),
  ('media.manage','media','manage','Cancel or delete an owned media task.',1,1,unixepoch(),unixepoch()),
  ('design.read','design','read','Read design or canvas state.',0,1,unixepoch(),unixepoch()),
  ('design.write','design','write','Mutate design or canvas state.',1,1,unixepoch(),unixepoch()),
  ('design.export','design','export','Export a design artifact.',1,1,unixepoch(),unixepoch()),
  ('drive.read','drive','read','Read connected drive content.',0,1,unixepoch(),unixepoch()),
  ('drive.write','drive','write','Mutate connected drive content.',1,1,unixepoch(),unixepoch()),
  ('platform.read','platform','read','Read platform health and metadata.',0,1,unixepoch(),unixepoch()),
  ('platform.audit','platform','audit','Read platform audit evidence.',0,1,unixepoch(),unixepoch()),
  ('platform.telemetry','platform','telemetry','Write platform telemetry.',1,1,unixepoch(),unixepoch());
