-- WIP: specialized agentsam_route_requirements (merge into 333_agentsam_route_tool_routing_priority_alignment.sql)
-- Generated by agentsam_route_tool_alignment_e2e.py
-- Safe to re-run. Uses UPDATE + INSERT one row per route_key because route_key is UNIQUE.

BEGIN TRANSACTION;

-- agent_cloudflare
UPDATE agentsam_route_requirements
SET

  task_type = 'deploy',
  mode = 'approved_mutation',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["develop","observe","operate"]',
  required_capability_keys_json = '[]',
  optional_capability_keys_json = '["worker.preview","logs.read","r2.read","r2.write","d1.read","github.read","github.write","terminal.execute"]',
  blocked_capability_keys_json = '["email.broadcast","secret.write"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 10,
  is_active = 1
WHERE route_key = 'agent_cloudflare';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_cloudflare',
  'deploy',
  'approved_mutation',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["develop","observe","operate"]',
  '[]',
  '["worker.preview","logs.read","r2.read","r2.write","d1.read","github.read","github.write","terminal.execute"]',
  '["email.broadcast","secret.write"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  10,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_cloudflare')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_cloudflare');

-- agent_code
UPDATE agentsam_route_requirements
SET

  task_type = 'develop',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["develop","inspect","observe"]',
  required_capability_keys_json = '["code.search"]',
  optional_capability_keys_json = '["github.read","github.write","terminal.execute","d1.read","r2.read"]',
  blocked_capability_keys_json = '["worker.deploy","email.broadcast","secret.write"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 12,
  is_active = 1
WHERE route_key = 'agent_code';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_code',
  'develop',
  'default',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["develop","inspect","observe"]',
  '["code.search"]',
  '["github.read","github.write","terminal.execute","d1.read","r2.read"]',
  '["worker.deploy","email.broadcast","secret.write"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  12,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_code')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_code');

-- agent_frontend
UPDATE agentsam_route_requirements
SET

  task_type = 'develop',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["develop","inspect","observe","design"]',
  required_capability_keys_json = '["code.search"]',
  optional_capability_keys_json = '["browser.inspect","github.read","github.write","r2.read","r2.write","worker.preview"]',
  blocked_capability_keys_json = '["email.broadcast","secret.write"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 12,
  is_active = 1
WHERE route_key = 'agent_frontend';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_frontend',
  'develop',
  'default',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["develop","inspect","observe","design"]',
  '["code.search"]',
  '["browser.inspect","github.read","github.write","r2.read","r2.write","worker.preview"]',
  '["email.broadcast","secret.write"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  12,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_frontend')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_frontend');

-- agent_database
UPDATE agentsam_route_requirements
SET

  task_type = 'database',
  mode = 'approved_mutation',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["develop","inspect","observe"]',
  required_capability_keys_json = '["d1.read"]',
  optional_capability_keys_json = '["d1.write","d1.batch_write","schema.inspect","logs.read"]',
  blocked_capability_keys_json = '["worker.deploy","email.broadcast","secret.write"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 8,
  is_active = 1
WHERE route_key = 'agent_database';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_database',
  'database',
  'approved_mutation',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["develop","inspect","observe"]',
  '["d1.read"]',
  '["d1.write","d1.batch_write","schema.inspect","logs.read"]',
  '["worker.deploy","email.broadcast","secret.write"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  8,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_database')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_database');

-- agent_terminal
UPDATE agentsam_route_requirements
SET

  task_type = 'deploy',
  mode = 'approved_mutation',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["develop","observe","operate"]',
  required_capability_keys_json = '[]',
  optional_capability_keys_json = '["terminal.execute","logs.read","github.read","d1.read","r2.read"]',
  blocked_capability_keys_json = '["email.broadcast","secret.write"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 8,
  is_active = 1
WHERE route_key = 'agent_terminal';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_terminal',
  'deploy',
  'approved_mutation',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["develop","observe","operate"]',
  '[]',
  '["terminal.execute","logs.read","github.read","d1.read","r2.read"]',
  '["email.broadcast","secret.write"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  8,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_terminal')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_terminal');

-- agent_debug
UPDATE agentsam_route_requirements
SET

  task_type = 'debug',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["inspect","observe","develop"]',
  required_capability_keys_json = '[]',
  optional_capability_keys_json = '["browser.inspect","logs.read","d1.read","r2.read","github.read","code.search","mcp.catalog.read"]',
  blocked_capability_keys_json = '["worker.deploy","email.broadcast","secret.write"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 8,
  is_active = 1
WHERE route_key = 'agent_debug';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_debug',
  'debug',
  'default',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["inspect","observe","develop"]',
  '[]',
  '["browser.inspect","logs.read","d1.read","r2.read","github.read","code.search","mcp.catalog.read"]',
  '["worker.deploy","email.broadcast","secret.write"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  8,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_debug')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_debug');

-- agent_tool_orchestration
UPDATE agentsam_route_requirements
SET

  task_type = 'tool_use',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["think","research","inspect","observe","develop","operate","integrate","admin"]',
  required_capability_keys_json = '["mcp.catalog.read"]',
  optional_capability_keys_json = '["mcp.tool.inspect","workflow.run","agent.run","d1.read","logs.read"]',
  blocked_capability_keys_json = '["worker.deploy","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 24,
  is_active = 1
WHERE route_key = 'agent_tool_orchestration';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_tool_orchestration',
  'tool_use',
  'default',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["think","research","inspect","observe","develop","operate","integrate","admin"]',
  '["mcp.catalog.read"]',
  '["mcp.tool.inspect","workflow.run","agent.run","d1.read","logs.read"]',
  '["worker.deploy","secret.write","email.broadcast"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  24,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_tool_orchestration')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_tool_orchestration');

-- agent_smoke_test
UPDATE agentsam_route_requirements
SET

  task_type = 'tool_use',
  mode = 'default_safe',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["inspect","observe","develop"]',
  required_capability_keys_json = '["mcp.catalog.read"]',
  optional_capability_keys_json = '["d1.read","logs.read","mcp.tool.inspect"]',
  blocked_capability_keys_json = '["worker.deploy","d1.write","d1.batch_write","terminal.execute","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 12,
  is_active = 1
WHERE route_key = 'agent_smoke_test';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_smoke_test',
  'tool_use',
  'default_safe',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["inspect","observe","develop"]',
  '["mcp.catalog.read"]',
  '["d1.read","logs.read","mcp.tool.inspect"]',
  '["worker.deploy","d1.write","d1.batch_write","terminal.execute","secret.write","email.broadcast"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  12,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_smoke_test')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_smoke_test');

-- agent_cost_audit
UPDATE agentsam_route_requirements
SET

  task_type = 'finance',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'mini',
  max_tier = 'standard',
  budget_priority = 'balanced',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["inspect","observe","integrate"]',
  required_capability_keys_json = '[]',
  optional_capability_keys_json = '["d1.read","logs.read","context.search","mcp.catalog.read"]',
  blocked_capability_keys_json = '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast","billing.mutate"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 6,
  is_active = 1
WHERE route_key = 'agent_cost_audit';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_cost_audit',
  'finance',
  'default',
  1,
  1,
  'mini',
  'standard',
  'balanced',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["inspect","observe","integrate"]',
  '[]',
  '["d1.read","logs.read","context.search","mcp.catalog.read"]',
  '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast","billing.mutate"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  6,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_cost_audit')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_cost_audit');

-- agent_research
UPDATE agentsam_route_requirements
SET

  task_type = 'research',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'mini',
  max_tier = 'standard',
  budget_priority = 'balanced',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["research","inspect","think"]',
  required_capability_keys_json = '[]',
  optional_capability_keys_json = '["context.search","memory.read","browser.inspect","mcp.catalog.read"]',
  blocked_capability_keys_json = '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 6,
  is_active = 1
WHERE route_key = 'agent_research';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_research',
  'research',
  'default',
  1,
  1,
  'mini',
  'standard',
  'balanced',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["research","inspect","think"]',
  '[]',
  '["context.search","memory.read","browser.inspect","mcp.catalog.read"]',
  '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  6,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_research')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_research');

-- agent_planning
UPDATE agentsam_route_requirements
SET

  task_type = 'plan',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'mini',
  max_tier = 'standard',
  budget_priority = 'balanced',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["think","research","inspect"]',
  required_capability_keys_json = '[]',
  optional_capability_keys_json = '["context.search","memory.read","d1.read","mcp.catalog.read"]',
  blocked_capability_keys_json = '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 6,
  is_active = 1
WHERE route_key = 'agent_planning';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_planning',
  'plan',
  'default',
  1,
  1,
  'mini',
  'standard',
  'balanced',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["think","research","inspect"]',
  '[]',
  '["context.search","memory.read","d1.read","mcp.catalog.read"]',
  '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  6,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_planning')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_planning');

-- agent_general
UPDATE agentsam_route_requirements
SET

  task_type = 'chat',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'mini',
  max_tier = 'standard',
  budget_priority = 'balanced',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["think","research","inspect"]',
  required_capability_keys_json = '[]',
  optional_capability_keys_json = '["memory.read","context.search","browser.inspect","d1.read","mcp.catalog.read"]',
  blocked_capability_keys_json = '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 4,
  is_active = 1
WHERE route_key = 'agent_general';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'agent_general',
  'chat',
  'default',
  1,
  1,
  'mini',
  'standard',
  'balanced',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["think","research","inspect"]',
  '[]',
  '["memory.read","context.search","browser.inspect","d1.read","mcp.catalog.read"]',
  '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  4,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'agent_general')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'agent_general');

-- cms_live_editor.discover_cms_schema
UPDATE agentsam_route_requirements
SET

  task_type = 'cms_schema',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["inspect","develop","design"]',
  required_capability_keys_json = '["d1.read"]',
  optional_capability_keys_json = '["cms.schema.read","r2.read","context.search"]',
  blocked_capability_keys_json = '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 8,
  is_active = 1
WHERE route_key = 'cms_live_editor.discover_cms_schema';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'cms_live_editor.discover_cms_schema',
  'cms_schema',
  'default',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["inspect","develop","design"]',
  '["d1.read"]',
  '["cms.schema.read","r2.read","context.search"]',
  '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  8,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'cms_live_editor.discover_cms_schema')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'cms_live_editor.discover_cms_schema');

-- cms_live_editor.design_template_library
UPDATE agentsam_route_requirements
SET

  task_type = 'cms_design',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["design","inspect","develop"]',
  required_capability_keys_json = '[]',
  optional_capability_keys_json = '["cms.template.read","r2.read","browser.inspect","context.search"]',
  blocked_capability_keys_json = '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 8,
  is_active = 1
WHERE route_key = 'cms_live_editor.design_template_library';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'cms_live_editor.design_template_library',
  'cms_design',
  'default',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["design","inspect","develop"]',
  '[]',
  '["cms.template.read","r2.read","browser.inspect","context.search"]',
  '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  8,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'cms_live_editor.design_template_library')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'cms_live_editor.design_template_library');

-- cms_live_editor.generate_dev_app_manifest
UPDATE agentsam_route_requirements
SET

  task_type = 'cms_manifest',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["develop","design","inspect"]',
  required_capability_keys_json = '[]',
  optional_capability_keys_json = '["cms.manifest.write","r2.read","r2.write","d1.read"]',
  blocked_capability_keys_json = '["worker.deploy","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 8,
  is_active = 1
WHERE route_key = 'cms_live_editor.generate_dev_app_manifest';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'cms_live_editor.generate_dev_app_manifest',
  'cms_manifest',
  'default',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["develop","design","inspect"]',
  '[]',
  '["cms.manifest.write","r2.read","r2.write","d1.read"]',
  '["worker.deploy","secret.write","email.broadcast"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  8,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'cms_live_editor.generate_dev_app_manifest')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'cms_live_editor.generate_dev_app_manifest');

-- cms_live_editor.write_r2_artifacts
UPDATE agentsam_route_requirements
SET

  task_type = 'cms_publish',
  mode = 'approved_mutation',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["develop","design","operate"]',
  required_capability_keys_json = '["r2.write"]',
  optional_capability_keys_json = '["r2.read","d1.read","cms.artifact.write"]',
  blocked_capability_keys_json = '["worker.deploy","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 8,
  is_active = 1
WHERE route_key = 'cms_live_editor.write_r2_artifacts';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'cms_live_editor.write_r2_artifacts',
  'cms_publish',
  'approved_mutation',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["develop","design","operate"]',
  '["r2.write"]',
  '["r2.read","d1.read","cms.artifact.write"]',
  '["worker.deploy","secret.write","email.broadcast"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  8,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'cms_live_editor.write_r2_artifacts')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'cms_live_editor.write_r2_artifacts');

-- cms_live_editor.verify_contract
UPDATE agentsam_route_requirements
SET

  task_type = 'cms_verify',
  mode = 'default',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["inspect","observe","develop"]',
  required_capability_keys_json = '[]',
  optional_capability_keys_json = '["browser.inspect","r2.read","d1.read","logs.read"]',
  blocked_capability_keys_json = '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 8,
  is_active = 1
WHERE route_key = 'cms_live_editor.verify_contract';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'cms_live_editor.verify_contract',
  'cms_verify',
  'default',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["inspect","observe","develop"]',
  '[]',
  '["browser.inspect","r2.read","d1.read","logs.read"]',
  '["worker.deploy","d1.write","terminal.execute","secret.write","email.broadcast"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  8,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'cms_live_editor.verify_contract')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'cms_live_editor.verify_contract');

-- cms_live_editor.promotion_gate
UPDATE agentsam_route_requirements
SET

  task_type = 'cms_approval',
  mode = 'approved_mutation',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'mini',
  max_tier = 'standard',
  budget_priority = 'balanced',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["inspect","observe","operate"]',
  required_capability_keys_json = '["approval.request"]',
  optional_capability_keys_json = '["d1.read","logs.read","r2.read"]',
  blocked_capability_keys_json = '["worker.deploy","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  max_tools = 6,
  is_active = 1
WHERE route_key = 'cms_live_editor.promotion_gate';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'cms_live_editor.promotion_gate',
  'cms_approval',
  'approved_mutation',
  1,
  1,
  'mini',
  'standard',
  'balanced',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["inspect","observe","operate"]',
  '["approval.request"]',
  '["d1.read","logs.read","r2.read"]',
  '["worker.deploy","secret.write","email.broadcast"]',
  '{"default":"allow","read":"allow","mutation":"approval_required","dangerous":"deny"}',
  6,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'cms_live_editor.promotion_gate')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'cms_live_editor.promotion_gate');

-- ollama-local-workflow-pinstest
UPDATE agentsam_route_requirements
SET

  task_type = 'local_test',
  mode = 'local_dev_dangerous',
  requires_tools = 1,
  requires_streaming = 1,
  preferred_tier = 'standard',
  max_tier = 'pro',
  budget_priority = 'quality',
  preferred_providers = '["openai","google","anthropic","workers_ai"]',
  blocked_providers = '[]',
  allowed_lanes_json = '["develop","observe"]',
  required_capability_keys_json = '[]',
  optional_capability_keys_json = '["terminal.execute","logs.read","workflow.run"]',
  blocked_capability_keys_json = '["worker.deploy","secret.write","email.broadcast"]',
  approval_policy_json = '{"default":"approval_required","read":"allow","mutation":"approval_required","dangerous":"approval_required"}',
  max_tools = 8,
  is_active = 1
WHERE route_key = 'ollama-local-workflow-pinstest';

INSERT INTO agentsam_route_requirements (
  route_key, task_type, mode, requires_tools, requires_streaming, preferred_tier, max_tier,
  budget_priority, preferred_providers, blocked_providers, allowed_lanes_json,
  required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json,
  approval_policy_json, max_tools, is_active
)
SELECT
  'ollama-local-workflow-pinstest',
  'local_test',
  'local_dev_dangerous',
  1,
  1,
  'standard',
  'pro',
  'quality',
  '["openai","google","anthropic","workers_ai"]',
  '[]',
  '["develop","observe"]',
  '[]',
  '["terminal.execute","logs.read","workflow.run"]',
  '["worker.deploy","secret.write","email.broadcast"]',
  '{"default":"approval_required","read":"allow","mutation":"approval_required","dangerous":"approval_required"}',
  8,
  1
WHERE EXISTS (SELECT 1 FROM agentsam_prompt_routes WHERE route_key = 'ollama-local-workflow-pinstest')
  AND NOT EXISTS (SELECT 1 FROM agentsam_route_requirements WHERE route_key = 'ollama-local-workflow-pinstest');

COMMIT;

-- Verification
SELECT route_key, task_type, mode, max_tools, allowed_lanes_json, required_capability_keys_json, optional_capability_keys_json, blocked_capability_keys_json
FROM agentsam_route_requirements
WHERE route_key IN (
  'agent_cloudflare',
  'agent_code',
  'agent_cost_audit',
  'agent_database',
  'agent_debug',
  'agent_frontend',
  'agent_general',
  'agent_planning',
  'agent_research',
  'agent_smoke_test',
  'agent_terminal',
  'agent_tool_orchestration',
  'cms_live_editor.design_template_library',
  'cms_live_editor.discover_cms_schema',
  'cms_live_editor.generate_dev_app_manifest',
  'cms_live_editor.promotion_gate',
  'cms_live_editor.verify_contract',
  'cms_live_editor.write_r2_artifacts',
  'ollama-local-workflow-pinstest'
)
ORDER BY route_key;
