-- agentsam_schema_unify.sql
-- Auto-generated by agentsam_schema_audit.py
-- Review each block before running against production

-- agentsam_execution_steps: rename legacy token columns
ALTER TABLE agentsam_execution_steps RENAME COLUMN tokens_in TO input_tokens;
ALTER TABLE agentsam_execution_steps RENAME COLUMN tokens_out TO output_tokens;

-- agentsam_skill_invocation: rename legacy token columns
ALTER TABLE agentsam_skill_invocation RENAME COLUMN tokens_in TO input_tokens;
ALTER TABLE agentsam_skill_invocation RENAME COLUMN tokens_out TO output_tokens;

-- agentsam_usage_rollups_daily: rename legacy token columns
ALTER TABLE agentsam_usage_rollups_daily RENAME COLUMN tokens_in TO input_tokens;
ALTER TABLE agentsam_usage_rollups_daily RENAME COLUMN tokens_out TO output_tokens;

-- agentsam_ai: add unix timestamp columns
ALTER TABLE agentsam_ai ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_ai SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_ai ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_ai SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_analytics: add unix timestamp columns
ALTER TABLE agentsam_analytics ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_analytics SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_analytics ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_analytics SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_approval_queue: add unix timestamp columns
ALTER TABLE agentsam_approval_queue ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_approval_queue SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_artifact_skills: add unix timestamp columns
ALTER TABLE agentsam_artifact_skills ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_artifact_skills SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_artifacts: add unix timestamp columns
ALTER TABLE agentsam_artifacts ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_artifacts SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_artifacts ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_artifacts SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_bootstrap: add unix timestamp columns
ALTER TABLE agentsam_bootstrap ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_bootstrap SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_bootstrap ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_bootstrap SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_browser_trusted_origin: add unix timestamp columns
ALTER TABLE agentsam_browser_trusted_origin ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_browser_trusted_origin SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_browser_trusted_origin ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_browser_trusted_origin SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_cad_jobs: add unix timestamp columns
ALTER TABLE agentsam_cad_jobs ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_cad_jobs SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_cad_jobs ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_cad_jobs SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_capability_aliases: add unix timestamp columns
ALTER TABLE agentsam_capability_aliases ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_capability_aliases SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_capability_aliases ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_capability_aliases SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_code_index_job: add unix timestamp columns
ALTER TABLE agentsam_code_index_job ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_code_index_job SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_command_pattern: add unix timestamp columns
ALTER TABLE agentsam_command_pattern ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_command_pattern SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_command_pattern ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_command_pattern SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_command_run: add unix timestamp columns
ALTER TABLE agentsam_command_run ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_command_run SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_context_digest: add unix timestamp columns
ALTER TABLE agentsam_context_digest ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_context_digest SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_context_digest ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_context_digest SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_cron_runs: add unix timestamp columns
ALTER TABLE agentsam_cron_runs ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_cron_runs SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_error_log: add unix timestamp columns
ALTER TABLE agentsam_error_log ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_error_log SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_execution_context: add unix timestamp columns
ALTER TABLE agentsam_execution_context ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_execution_context SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_execution_dependency_graph: add unix timestamp columns
ALTER TABLE agentsam_execution_dependency_graph ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_execution_dependency_graph SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_execution_dependency_graph ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_execution_dependency_graph SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_execution_performance_metrics: add unix timestamp columns

-- agentsam_executions: add unix timestamp columns
ALTER TABLE agentsam_executions ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_executions SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_feature_flag: add unix timestamp columns
ALTER TABLE agentsam_feature_flag ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_feature_flag SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_feature_flag ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_feature_flag SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_fetch_domain_allowlist: add unix timestamp columns
ALTER TABLE agentsam_fetch_domain_allowlist ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_fetch_domain_allowlist SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_guardrail_events: add unix timestamp columns
ALTER TABLE agentsam_guardrail_events ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_guardrail_events SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_guardrail_rulesets: add unix timestamp columns
ALTER TABLE agentsam_guardrail_rulesets ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_guardrail_rulesets SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_guardrail_rulesets ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_guardrail_rulesets SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_health_daily: add unix timestamp columns

-- agentsam_hook: add unix timestamp columns
ALTER TABLE agentsam_hook ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_hook SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_ignore_pattern: add unix timestamp columns
ALTER TABLE agentsam_ignore_pattern ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_ignore_pattern SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_ignore_pattern ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_ignore_pattern SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_mcp_allowlist: add unix timestamp columns
ALTER TABLE agentsam_mcp_allowlist ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_mcp_allowlist SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_mcp_servers: add unix timestamp columns
ALTER TABLE agentsam_mcp_servers ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_mcp_servers SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_mcp_servers ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_mcp_servers SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_memory: add unix timestamp columns
ALTER TABLE agentsam_memory ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_memory SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_memory ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_memory SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_model_catalog: add unix timestamp columns
ALTER TABLE agentsam_model_catalog ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_model_catalog SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_model_catalog ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_model_catalog SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_model_pricing: add unix timestamp columns
ALTER TABLE agentsam_model_pricing ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_model_pricing SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_model_pricing ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_model_pricing SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_model_routing_memory: add unix timestamp columns
ALTER TABLE agentsam_model_routing_memory ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_model_routing_memory SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_model_routing_memory ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_model_routing_memory SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_patch_sessions: add unix timestamp columns
ALTER TABLE agentsam_patch_sessions ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_patch_sessions SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_performance_eto_events: add unix timestamp columns
ALTER TABLE agentsam_performance_eto_events ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_performance_eto_events SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_plan_tasks: add unix timestamp columns
ALTER TABLE agentsam_plan_tasks ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_plan_tasks SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_plans: add unix timestamp columns
ALTER TABLE agentsam_plans ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_plans SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_plans ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_plans SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_project_context: add unix timestamp columns
ALTER TABLE agentsam_project_context ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_project_context SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_project_context ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_project_context SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_prompt_cache_keys: add unix timestamp columns

-- agentsam_prompt_routes: add unix timestamp columns
ALTER TABLE agentsam_prompt_routes ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_prompt_routes SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_prompt_routes ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_prompt_routes SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_prompt_versions: add unix timestamp columns
ALTER TABLE agentsam_prompt_versions ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_prompt_versions SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_routing_arms: add unix timestamp columns
ALTER TABLE agentsam_routing_arms ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_routing_arms SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_skill: add unix timestamp columns
ALTER TABLE agentsam_skill ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_skill SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_skill ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_skill SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_skill_revision: add unix timestamp columns
ALTER TABLE agentsam_skill_revision ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_skill_revision SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_slash_commands: add unix timestamp columns
ALTER TABLE agentsam_slash_commands ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_slash_commands SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;

-- agentsam_subagent_profile: add unix timestamp columns
ALTER TABLE agentsam_subagent_profile ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_subagent_profile SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_subagent_profile ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_subagent_profile SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_subscription_registry: add unix timestamp columns
ALTER TABLE agentsam_subscription_registry ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_subscription_registry SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_subscription_registry ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_subscription_registry SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_task_slos: add unix timestamp columns
ALTER TABLE agentsam_task_slos ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_task_slos SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_tool_cache: add unix timestamp columns
ALTER TABLE agentsam_tool_cache ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_tool_cache SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_tool_cache ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_tool_cache SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_tool_chain: add unix timestamp columns

-- agentsam_tool_stats_compacted: add unix timestamp columns

-- agentsam_tools: add unix timestamp columns
ALTER TABLE agentsam_tools ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_tools SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_tools ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_tools SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_usage_rollups_daily: add unix timestamp columns

-- agentsam_user_feature_override: add unix timestamp columns
ALTER TABLE agentsam_user_feature_override ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_user_feature_override SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_user_policy: add unix timestamp columns
ALTER TABLE agentsam_user_policy ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_user_policy SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_webhook_weekly: add unix timestamp columns

-- agentsam_workflow_handlers: add unix timestamp columns
ALTER TABLE agentsam_workflow_handlers ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_workflow_handlers SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_workflow_handlers ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_workflow_handlers SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_workspace: add unix timestamp columns
ALTER TABLE agentsam_workspace ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_workspace SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_workspace ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_workspace SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_workspace_state: add unix timestamp columns
ALTER TABLE agentsam_workspace_state ADD COLUMN created_at_unix INTEGER;
-- UPDATE agentsam_workspace_state SET created_at_unix = strftime('%s', created_at) WHERE created_at_unix IS NULL;
ALTER TABLE agentsam_workspace_state ADD COLUMN updated_at_unix INTEGER;
-- UPDATE agentsam_workspace_state SET updated_at_unix = strftime('%s', updated_at) WHERE updated_at_unix IS NULL;

-- agentsam_ai: total_cost_usd should not be nullable
-- UPDATE agentsam_ai SET total_cost_usd = 0 WHERE total_cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_command_run: cost_usd should not be nullable
-- UPDATE agentsam_command_run SET cost_usd = 0 WHERE cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_eval_runs: cost_usd should not be nullable
-- UPDATE agentsam_eval_runs SET cost_usd = 0 WHERE cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_execution_performance_metrics: total_cost_usd should not be nullable
-- UPDATE agentsam_execution_performance_metrics SET total_cost_usd = 0 WHERE total_cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_execution_steps: cost_usd should not be nullable
-- UPDATE agentsam_execution_steps SET cost_usd = 0 WHERE cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_executions: cost_usd should not be nullable
-- UPDATE agentsam_executions SET cost_usd = 0 WHERE cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_mcp_tool_execution: cost_usd should not be nullable
-- UPDATE agentsam_mcp_tool_execution SET cost_usd = 0 WHERE cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_mcp_workflows: total_cost_usd should not be nullable
-- UPDATE agentsam_mcp_workflows SET total_cost_usd = 0 WHERE total_cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_patch_sessions: cost_usd should not be nullable
-- UPDATE agentsam_patch_sessions SET cost_usd = 0 WHERE cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_plan_tasks: cost_usd should not be nullable
-- UPDATE agentsam_plan_tasks SET cost_usd = 0 WHERE cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_skill_invocation: cost_usd should not be nullable
-- UPDATE agentsam_skill_invocation SET cost_usd = 0 WHERE cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_tool_call_log: cost_usd should not be nullable
-- UPDATE agentsam_tool_call_log SET cost_usd = 0 WHERE cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_tool_stats_compacted: total_cost_usd should not be nullable
-- UPDATE agentsam_tool_stats_compacted SET total_cost_usd = 0 WHERE total_cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_webhook_events: cost_usd should not be nullable
-- UPDATE agentsam_webhook_events SET cost_usd = 0 WHERE cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)

-- agentsam_webhook_weekly: total_cost_usd should not be nullable
-- UPDATE agentsam_webhook_weekly SET total_cost_usd = 0 WHERE total_cost_usd IS NULL;
-- (SQLite cannot ALTER NOT NULL after creation — rebuild table to enforce)
