#!/usr/bin/env python3
"""Render IAM-branded quality report HTML from Playwright results.json."""

from __future__ import annotations

import html
import json
import os
import re
import sys
from pathlib import Path

TEMPLATE_DIR = Path(__file__).resolve().parent
REPO_ROOT = TEMPLATE_DIR.parents[1]

WORKSPACE = os.getenv("IAM_WORKSPACE_SLUG", "inneranimalmedia")
BRAND = os.getenv("IAM_BRAND_NAME", "Inner Animal Media")
TAGLINE = os.getenv("IAM_REPORT_TAGLINE", "Automate. Validate. Elevate.")
FOOTER_COPY = os.getenv(
    "IAM_REPORT_FOOTER_COPY",
    "Generated by Inner Animal Media.<br>Hosted quality evidence for this workspace.",
)
GENERATED_LABEL = os.getenv("IAM_REPORT_GENERATED_LABEL", "Automated QA")
PUBLIC_BASE = os.getenv(
    "IAM_PUBLIC_REPORT_BASE",
    "https://inneranimalmedia.com/qualityreport",
)
HEADER_LOGO = os.getenv(
    "IAM_HEADER_LOGO",
    "https://imagedelivery.net/g7wf09fCONpnidkRnR_5vw/ac515729-af6b-4ea5-8b10-e581a4d02100/thumbnail",
)
FOOTER_LOGO = os.getenv(
    "IAM_FOOTER_LOGO",
    "https://imagedelivery.net/g7wf09fCONpnidkRnR_5vw/11f6af46-0a3c-482a-abe8-83edc5a8a200/avatar",
)

CAPTURES_ROOT = Path(os.getenv("IAM_CAPTURES_ROOT", REPO_ROOT / "captures" / WORKSPACE))
STAGING_ROOT = Path(os.getenv("IAM_REPORTS_STAGING_ROOT", REPO_ROOT / "reports" / ".staging" / WORKSPACE))
RESULTS_JSON = Path(os.getenv("IAM_RESULTS_JSON", CAPTURES_ROOT / "results.json"))
OUT_DIR = Path(os.getenv("IAM_REPORT_OUT_DIR", CAPTURES_ROOT / "report"))
OUT_HTML = OUT_DIR / "index.html"


def esc(value: object) -> str:
    return html.escape(str(value or ""))


def load_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def apply_placeholders(text: str, mapping: dict[str, str]) -> str:
    for key, value in mapping.items():
        text = text.replace(f"{{{{{key}}}}}", value)
    return text


def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def raw_report_prefix() -> str:
    if (CAPTURES_ROOT / "raw-playwright-report").exists():
        return "raw-playwright-report"
    return "raw-quality-report"


def find_artifacts(test_title: str) -> dict[str, list[dict[str, str]]]:
    safe_words = [w for w in re.split(r"[^a-zA-Z0-9]+", test_title.lower()) if len(w) > 2]
    matches: list[tuple[int, Path]] = []
    results_dir = CAPTURES_ROOT / "results"
    if not results_dir.exists():
        return {"screenshots": [], "videos": [], "traces": [], "errors": [], "other": []}

    for path in results_dir.glob("**/*"):
        if not path.is_file():
            continue
        low = str(path).lower()
        score = sum(1 for word in safe_words if word in low)
        if score:
            matches.append((score, path))

    matches.sort(key=lambda item: item[0], reverse=True)
    files = [path for _, path in matches[:8]]
    prefix = raw_report_prefix()

    out: dict[str, list[dict[str, str]]] = {
        "screenshots": [],
        "videos": [],
        "traces": [],
        "errors": [],
        "other": [],
    }
    for path in files:
        rel = path.relative_to(CAPTURES_ROOT)
        href = f"../{rel.as_posix()}"
        suffix = path.suffix.lower()
        name = path.name
        item = {"name": name, "href": href}
        if suffix in {".png", ".jpg", ".jpeg", ".webp"}:
            if re.search(r"test-(finished|failed)", name, re.I):
                continue
            out["screenshots"].append(item)
        elif suffix in {".webm", ".mp4"}:
            out["videos"].append(item)
        elif suffix == ".zip" and "trace" in name.lower():
            item["trace_viewer"] = (
                f"{PUBLIC_BASE}/{prefix}/trace/index.html?trace={PUBLIC_BASE}/{rel.as_posix()}"
            )
            out["traces"].append(item)
        elif name == "error-context.md" or suffix in {".md", ".txt", ".json"}:
            out["errors"].append(item)
        else:
            out["other"].append(item)
    return out


def walk_suite(suite: dict, ancestors: list[str] | None = None) -> list[dict]:
    ancestors = ancestors or []
    title = suite.get("title")
    path = [*ancestors, title] if title else ancestors
    tests: list[dict] = []

    for spec in suite.get("specs", []):
        spec_title = spec.get("title", "Untitled")
        for test in spec.get("tests", []):
            results = test.get("results", [])
            status = test.get("outcome") or test.get("status") or "unknown"
            duration = sum(result.get("duration", 0) for result in results)
            errors: list[str] = []
            for result in results:
                for error in result.get("errors", []):
                    message = error.get("message") or error.get("stack") or str(error)
                    if message:
                        errors.append(message)
            title_full = " › ".join(part for part in [*path, spec_title] if part)
            tests.append(
                {
                    "title": title_full,
                    "status": status,
                    "duration": duration,
                    "errors": errors,
                    "artifacts": find_artifacts(title_full),
                }
            )

    for child in suite.get("suites", []):
        tests.extend(walk_suite(child, path))
    return tests


def status_label(status: str) -> str:
    return {"expected": "passed", "unexpected": "failed"}.get(status, status)


def artifact_html(test: dict) -> str:
    artifacts = test["artifacts"]
    parts: list[str] = []

    if test["errors"]:
        err = "\n\n".join(test["errors"][:2])
        parts.append(f"<details open><summary>Errors</summary><pre>{esc(err)}</pre></details>")

    if artifacts["screenshots"]:
        imgs = "".join(
            f"<a href='{esc(item['href'])}' target='_blank' rel='noopener'>"
            f"<img src='{esc(item['href'])}' alt='{esc(item['name'])}'></a>"
            for item in artifacts["screenshots"]
        )
        parts.append(
            f"<details open><summary>Screenshots</summary><div class='media-grid'>{imgs}</div></details>"
        )

    if artifacts["videos"]:
        vids = "".join(
            f"<video controls src='{esc(item['href'])}'></video>" for item in artifacts["videos"]
        )
        parts.append(
            f"<details><summary>Recordings</summary><div class='media-grid'>{vids}</div></details>"
        )

    if artifacts["traces"]:
        links = "".join(
            f"<a class='pill' href='{esc(item['href'])}' target='_blank' rel='noopener'>trace.zip</a>"
            for item in artifacts["traces"]
        )
        parts.append(f"<details><summary>Trace Data</summary><div class='links'>{links}</div></details>")

    if artifacts["errors"]:
        links = "".join(
            f"<a class='pill' href='{esc(item['href'])}' target='_blank' rel='noopener'>{esc(item['name'])}</a>"
            for item in artifacts["errors"]
        )
        parts.append(f"<details><summary>Evidence Files</summary><div class='links'>{links}</div></details>")

    return "".join(parts) or "<p class='muted'>No attached artifacts for this test.</p>"


def spec_title_low(full_title: str) -> str:
    parts = [p.strip().lower() for p in full_title.split("›")]
    return parts[-1] if parts else full_title.lower()


def merge_staging_evidence_screenshots(rows: list[dict]) -> None:
    evidence_dir = STAGING_ROOT / "evidence"
    if not evidence_dir.is_dir():
        return
    for path in evidence_dir.glob("*.json"):
        try:
            ev = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        slug = path.stem
        r2_key = str(ev.get("r2_key") or ev.get("screenshotPath") or "").strip()
        href = f"screenshots/{slug}.png"
        name_hint = str(ev.get("name") or slug).lower()
        ev_path = str(ev.get("path") or "").strip().lower()
        for row in rows:
            spec = spec_title_low(row["title"])
            path_match = ev_path and ev_path.lstrip("/") in spec.replace(" ", "")
            name_match = name_hint in spec or slug.replace("-", " ") in spec
            if not (path_match or name_match):
                continue
            shot = {"name": f"{slug}.png", "href": href}
            if r2_key:
                shot["r2_key"] = r2_key
            row["artifacts"]["screenshots"] = [shot]
            break


def render_test_rows(tests: list[dict]) -> str:
    row_template = load_text(TEMPLATE_DIR / "partials" / "test-row.html")
    rows: list[str] = []
    for test in tests:
        status = status_label(test["status"])
        rows.append(
            apply_placeholders(
                row_template,
                {
                    "TITLE": esc(test["title"]),
                    "STATUS": esc(status),
                    "DURATION": esc(test["duration"]),
                    "ARTIFACTS": artifact_html(test),
                },
            )
        )
    if not rows:
        return "<div class='empty'>No tests found. Run Playwright first.</div>"
    return "\n".join(rows)


def diagnostic_step_html(test: dict) -> str:
    status = status_label(test["status"])
    body = artifact_html(test)
    return (
        f"<details class='test-row' open>"
        f"<summary><span>{esc(test['title'])}</span>"
        f"<span class='status {esc(status)}'>{esc(status)}</span>"
        f"<span>{esc(test['duration'])}ms</span></summary>"
        f"<div class='test-detail'>{body}</div></details>"
    )


def render_diagnostics(tests: list[dict], out_path: Path) -> None:
    trace_links: list[str] = []
    traces_dir = CAPTURES_ROOT / "results"
    if traces_dir.exists():
        for path in sorted(traces_dir.glob("**/*.zip")):
            if "trace" not in path.name.lower():
                continue
            rel = path.relative_to(CAPTURES_ROOT)
            href = f"traces/{path.name}"
            trace_links.append(
                f"<a class='pill' href='{esc(href)}' download>{esc(path.name)}</a>"
            )

    run_id = os.getenv("REPORT_DATE", "") + "/" + os.getenv("REPORT_TIME", "")
    rows = "\n".join(diagnostic_step_html(t) for t in tests) or "<p class='empty'>No tests in this run.</p>"
    trace_block = " ".join(trace_links) if trace_links else "<span class='muted'>No trace archives for this run.</span>"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    html_out = apply_placeholders(
        load_text(TEMPLATE_DIR / "diagnostics.html"),
        {
            "STYLES": load_text(TEMPLATE_DIR / "styles.css"),
            "WORKSPACE": esc(WORKSPACE),
            "HEADER_LOGO": esc(HEADER_LOGO),
            "FOOTER_LOGO": esc(FOOTER_LOGO),
            "GENERATED_LABEL": esc(GENERATED_LABEL),
            "RUN_ID": esc(run_id.strip("/") or "pending"),
            "DIAGNOSTIC_ROWS": rows,
            "TRACE_LINKS": trace_block,
        },
    )
    out_path.write_text(html_out, encoding="utf-8")


def render_report() -> Path:
    data = load_json(RESULTS_JSON)
    tests: list[dict] = []
    for suite in data.get("suites", []):
        tests.extend(walk_suite(suite))

    merge_staging_evidence_screenshots(tests)

    total = len(tests)
    passed = sum(1 for test in tests if test["status"] in ("expected", "passed"))
    failed = sum(1 for test in tests if test["status"] in ("unexpected", "failed"))
    flaky = sum(1 for test in tests if test["status"] == "flaky")
    skipped = sum(1 for test in tests if test["status"] == "skipped")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    html_out = apply_placeholders(
        load_text(TEMPLATE_DIR / "index.html"),
        {
            "PAGE_TITLE": esc("Inner Animal Media Quality Report"),
            "STYLES": load_text(TEMPLATE_DIR / "styles.css"),
            "BRAND": esc(BRAND),
            "WORKSPACE": esc(WORKSPACE),
            "HEADER_LOGO": esc(HEADER_LOGO),
            "FOOTER_LOGO": esc(FOOTER_LOGO),
            "TAGLINE": esc(TAGLINE),
            "FOOTER_COPY": FOOTER_COPY,
            "GENERATED_LABEL": esc(GENERATED_LABEL),
            "TOTAL": esc(total),
            "PASSED": esc(passed),
            "FAILED": esc(failed),
            "FLAKY": esc(flaky),
            "SKIPPED": esc(skipped),
            "TEST_ROWS": render_test_rows(tests),
        },
    )
    OUT_HTML.write_text(html_out, encoding="utf-8")
    render_diagnostics(tests, OUT_DIR / "diagnostics-index.html")
    return OUT_HTML


def main() -> int:
    if not RESULTS_JSON.exists():
        print(f"Missing results file: {RESULTS_JSON}", file=sys.stderr)
        return 1
    output = render_report()
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
