// AUTO-GENERATED from VS Code/Cursor theme-seti — do not hand-edit
export type SetiGlyphDef = { char: string; color: string };

export const SETI_GLYPHS: Record<string, SetiGlyphDef> = {
  "R": { char: "\u0001", color: "#519aba" },
  "argdown": { char: "\u0003", color: "#519aba" },
  "asm": { char: "\u0004", color: "#cc3e44" },
  "audio": { char: "\u0005", color: "#a074c4" },
  "babel": { char: "\u0006", color: "#cbcb41" },
  "bazel": { char: "\u0007", color: "#8dc149" },
  "bazel_1": { char: "\u0007", color: "#4d5a5e" },
  "bicep": { char: "\b", color: "#519aba" },
  "bower": { char: "\t", color: "#e37933" },
  "bsl": { char: "\n", color: "#cc3e44" },
  "c": { char: "\f", color: "#519aba" },
  "c-sharp": { char: "\u000b", color: "#519aba" },
  "c_1": { char: "\f", color: "#a074c4" },
  "c_2": { char: "\f", color: "#cbcb41" },
  "cake": { char: "\r", color: "#cc3e44" },
  "cake_php": { char: "\u000e", color: "#cc3e44" },
  "clock": { char: "\u0012", color: "#519aba" },
  "clock_1": { char: "\u0012", color: "#6d8086" },
  "clojure": { char: "\u0013", color: "#8dc149" },
  "clojure_1": { char: "\u0013", color: "#519aba" },
  "code-climate": { char: "\u0014", color: "#8dc149" },
  "code-search": { char: "\u0015", color: "#a074c4" },
  "coffee": { char: "\u0016", color: "#cbcb41" },
  "coldfusion": { char: "\u0018", color: "#519aba" },
  "config": { char: "\u0019", color: "#6d8086" },
  "cpp": { char: "\u001a", color: "#519aba" },
  "cpp_1": { char: "\u001a", color: "#a074c4" },
  "cpp_2": { char: "\u001a", color: "#cbcb41" },
  "crystal": { char: "\u001b", color: "#d4d7d6" },
  "crystal_embedded": { char: "\u001c", color: "#d4d7d6" },
  "css": { char: "\u001d", color: "#519aba" },
  "csv": { char: "\u001e", color: "#8dc149" },
  "cu": { char: "\u001f", color: "#8dc149" },
  "cu_1": { char: "\u001f", color: "#a074c4" },
  "d": { char: " ", color: "#cc3e44" },
  "dart": { char: "!", color: "#519aba" },
  "db": { char: "\"", color: "#f55385" },
  "db_1": { char: "\"", color: "#519aba" },
  "default": { char: "#", color: "#d4d7d6" },
  "docker": { char: "%", color: "#519aba" },
  "docker_1": { char: "%", color: "#4d5a5e" },
  "docker_2": { char: "%", color: "#8dc149" },
  "docker_3": { char: "%", color: "#f55385" },
  "ejs": { char: "'", color: "#cbcb41" },
  "elixir": { char: "(", color: "#a074c4" },
  "elixir_script": { char: ")", color: "#a074c4" },
  "elm": { char: "*", color: "#519aba" },
  "eslint": { char: ",", color: "#a074c4" },
  "eslint_1": { char: ",", color: "#4d5a5e" },
  "ethereum": { char: "-", color: "#519aba" },
  "f-sharp": { char: ".", color: "#519aba" },
  "favicon": { char: "/", color: "#cbcb41" },
  "firebase": { char: "0", color: "#e37933" },
  "firefox": { char: "1", color: "#e37933" },
  "font": { char: "3", color: "#cc3e44" },
  "git": { char: "4", color: "#41535b" },
  "github": { char: "7", color: "#d4d7d6" },
  "gitlab": { char: "8", color: "#e37933" },
  "go": { char: "9", color: "#519aba" },
  "go2": { char: ":", color: "#519aba" },
  "godot": { char: ";", color: "#519aba" },
  "godot_1": { char: ";", color: "#cc3e44" },
  "godot_2": { char: ";", color: "#cbcb41" },
  "godot_3": { char: ";", color: "#a074c4" },
  "gradle": { char: "<", color: "#519aba" },
  "grails": { char: "=", color: "#8dc149" },
  "graphql": { char: ">", color: "#f55385" },
  "grunt": { char: "?", color: "#e37933" },
  "gulp": { char: "@", color: "#cc3e44" },
  "hacklang": { char: "A", color: "#e37933" },
  "haml": { char: "B", color: "#cc3e44" },
  "happenings": { char: "C", color: "#519aba" },
  "haskell": { char: "D", color: "#a074c4" },
  "haxe": { char: "E", color: "#e37933" },
  "haxe_1": { char: "E", color: "#cbcb41" },
  "haxe_2": { char: "E", color: "#519aba" },
  "haxe_3": { char: "E", color: "#a074c4" },
  "heroku": { char: "F", color: "#a074c4" },
  "hex": { char: "G", color: "#cc3e44" },
  "html": { char: "H", color: "#519aba" },
  "html_1": { char: "H", color: "#8dc149" },
  "html_2": { char: "H", color: "#cbcb41" },
  "html_3": { char: "H", color: "#e37933" },
  "html_erb": { char: "I", color: "#cc3e44" },
  "ignored": { char: "J", color: "#41535b" },
  "illustrator": { char: "K", color: "#cbcb41" },
  "image": { char: "L", color: "#a074c4" },
  "info": { char: "M", color: "#519aba" },
  "ionic": { char: "N", color: "#519aba" },
  "jade": { char: "O", color: "#cc3e44" },
  "java": { char: "P", color: "#cc3e44" },
  "java_1": { char: "P", color: "#519aba" },
  "javascript": { char: "Q", color: "#cbcb41" },
  "javascript_1": { char: "Q", color: "#e37933" },
  "javascript_2": { char: "Q", color: "#519aba" },
  "jenkins": { char: "R", color: "#cc3e44" },
  "jinja": { char: "S", color: "#cc3e44" },
  "json": { char: "U", color: "#cbcb41" },
  "json_1": { char: "U", color: "#8dc149" },
  "julia": { char: "V", color: "#a074c4" },
  "karma": { char: "W", color: "#8dc149" },
  "kotlin": { char: "X", color: "#e37933" },
  "less": { char: "Y", color: "#519aba" },
  "license": { char: "Z", color: "#cbcb41" },
  "license_1": { char: "Z", color: "#e37933" },
  "license_2": { char: "Z", color: "#cc3e44" },
  "liquid": { char: "[", color: "#8dc149" },
  "livescript": { char: "\\", color: "#519aba" },
  "lock": { char: "]", color: "#8dc149" },
  "lua": { char: "^", color: "#519aba" },
  "makefile": { char: "_", color: "#e37933" },
  "makefile_1": { char: "_", color: "#a074c4" },
  "makefile_2": { char: "_", color: "#6d8086" },
  "makefile_3": { char: "_", color: "#519aba" },
  "markdown": { char: "`", color: "#519aba" },
  "maven": { char: "a", color: "#cc3e44" },
  "mdo": { char: "b", color: "#cc3e44" },
  "mustache": { char: "c", color: "#e37933" },
  "nim": { char: "e", color: "#cbcb41" },
  "notebook": { char: "f", color: "#519aba" },
  "npm": { char: "g", color: "#41535b" },
  "npm_1": { char: "g", color: "#cc3e44" },
  "npm_ignored": { char: "h", color: "#41535b" },
  "nunjucks": { char: "i", color: "#8dc149" },
  "ocaml": { char: "j", color: "#e37933" },
  "odata": { char: "k", color: "#e37933" },
  "pddl": { char: "l", color: "#a074c4" },
  "pdf": { char: "m", color: "#cc3e44" },
  "perl": { char: "n", color: "#519aba" },
  "photoshop": { char: "o", color: "#519aba" },
  "php": { char: "p", color: "#a074c4" },
  "pipeline": { char: "q", color: "#e37933" },
  "plan": { char: "r", color: "#8dc149" },
  "platformio": { char: "s", color: "#e37933" },
  "powershell": { char: "t", color: "#519aba" },
  "prisma": { char: "u", color: "#519aba" },
  "prolog": { char: "w", color: "#e37933" },
  "pug": { char: "x", color: "#cc3e44" },
  "puppet": { char: "y", color: "#cbcb41" },
  "purescript": { char: "z", color: "#d4d7d6" },
  "python": { char: "{", color: "#519aba" },
  "react": { char: "}", color: "#519aba" },
  "react_1": { char: "}", color: "#e37933" },
  "reasonml": { char: "~", color: "#cc3e44" },
  "rescript": { char: "\u007f", color: "#cc3e44" },
  "rescript_1": { char: "\u007f", color: "#f55385" },
  "rollup": { char: "\u0080", color: "#cc3e44" },
  "ruby": { char: "\u0081", color: "#cc3e44" },
  "rust": { char: "\u0082", color: "#6d8086" },
  "salesforce": { char: "\u0083", color: "#519aba" },
  "sass": { char: "\u0084", color: "#f55385" },
  "sbt": { char: "\u0085", color: "#519aba" },
  "scala": { char: "\u0086", color: "#cc3e44" },
  "shell": { char: "\u0089", color: "#8dc149" },
  "slim": { char: "\u008a", color: "#e37933" },
  "smarty": { char: "\u008b", color: "#cbcb41" },
  "spring": { char: "\u008c", color: "#8dc149" },
  "stylelint": { char: "\u008d", color: "#d4d7d6" },
  "stylelint_1": { char: "\u008d", color: "#4d5a5e" },
  "stylus": { char: "\u008e", color: "#8dc149" },
  "sublime": { char: "\u008f", color: "#e37933" },
  "svelte": { char: "\u0090", color: "#cc3e44" },
  "svg": { char: "\u0091", color: "#a074c4" },
  "svg_1": { char: "\u0091", color: "#519aba" },
  "swift": { char: "\u0092", color: "#e37933" },
  "terraform": { char: "\u0093", color: "#a074c4" },
  "tex": { char: "\u0094", color: "#519aba" },
  "tex_1": { char: "\u0094", color: "#cbcb41" },
  "tex_2": { char: "\u0094", color: "#e37933" },
  "tex_3": { char: "\u0094", color: "#d4d7d6" },
  "todo": { char: "\u0096", color: "#d4d7d6" },
  "tsconfig": { char: "\u0097", color: "#519aba" },
  "twig": { char: "\u0098", color: "#8dc149" },
  "typescript": { char: "\u0099", color: "#519aba" },
  "typescript_1": { char: "\u0099", color: "#e37933" },
  "vala": { char: "\u009a", color: "#6d8086" },
  "video": { char: "\u009b", color: "#f55385" },
  "vite": { char: "\u009c", color: "#cbcb41" },
  "vue": { char: "\u009d", color: "#8dc149" },
  "wasm": { char: "\u009e", color: "#a074c4" },
  "wat": { char: "\u009f", color: "#a074c4" },
  "webpack": { char: "\u00a0", color: "#519aba" },
  "wgt": { char: "\u00a1", color: "#519aba" },
  "windows": { char: "\u00a2", color: "#519aba" },
  "word": { char: "\u00a3", color: "#519aba" },
  "xls": { char: "\u00a4", color: "#8dc149" },
  "xml": { char: "\u00a5", color: "#e37933" },
  "yarn": { char: "\u00a6", color: "#519aba" },
  "yml": { char: "\u00a7", color: "#a074c4" },
  "zig": { char: "\u00a8", color: "#e37933" },
  "zip": { char: "\u00a9", color: "#cc3e44" },
  "zip_1": { char: "\u00a9", color: "#6d8086" }
};

export const SETI_FILE_EXTENSIONS: Record<string, string> = {
  "bsl": "bsl",
  "mdo": "mdo",
  "cls": "salesforce",
  "apex": "salesforce",
  "asm": "asm",
  "s": "asm",
  "bicep": "bicep",
  "bzl": "bazel",
  "bazel": "bazel",
  "build": "bazel",
  "workspace": "bazel",
  "bazelignore": "bazel",
  "bazelversion": "bazel",
  "h": "c_1",
  "aspx": "html",
  "ascx": "html_1",
  "asax": "html_2",
  "master": "html_2",
  "hh": "cpp_1",
  "hpp": "cpp_1",
  "hxx": "cpp_1",
  "h++": "cpp_1",
  "edn": "clojure_1",
  "cfc": "coldfusion",
  "cfm": "coldfusion",
  "litcoffee": "coffee",
  "config": "config",
  "cr": "crystal",
  "ecr": "crystal_embedded",
  "slang": "crystal_embedded",
  "cson": "json",
  "css.map": "css",
  "sss": "css",
  "csv": "csv",
  "xls": "xls",
  "xlsx": "xls",
  "cuh": "cu_1",
  "hu": "cu_1",
  "cake": "cake",
  "ctp": "cake_php",
  "d": "d",
  "doc": "word",
  "docx": "word",
  "ejs": "ejs",
  "ex": "elixir",
  "exs": "elixir_script",
  "elm": "elm",
  "ico": "favicon",
  "gitconfig": "git",
  "gitkeep": "git",
  "gitattributes": "git",
  "gitmodules": "git",
  "slide": "go",
  "article": "go",
  "gd": "godot",
  "godot": "godot_1",
  "tres": "godot_2",
  "tscn": "godot_3",
  "gradle": "gradle",
  "gsp": "grails",
  "gql": "graphql",
  "graphql": "graphql",
  "graphqls": "graphql",
  "hack": "hacklang",
  "haml": "haml",
  "hs": "haskell",
  "lhs": "haskell",
  "hx": "haxe",
  "hxs": "haxe_1",
  "hxp": "haxe_2",
  "hxml": "haxe_3",
  "jade": "jade",
  "class": "java_1",
  "classpath": "java",
  "js.map": "javascript",
  "cjs.map": "javascript",
  "mjs.map": "javascript",
  "spec.js": "javascript_1",
  "spec.cjs": "javascript_1",
  "spec.mjs": "javascript_1",
  "test.js": "javascript_1",
  "test.cjs": "javascript_1",
  "test.mjs": "javascript_1",
  "es": "javascript",
  "es5": "javascript",
  "es7": "javascript",
  "jinja": "jinja",
  "jinja2": "jinja",
  "kt": "kotlin",
  "kts": "kotlin",
  "liquid": "liquid",
  "ls": "livescript",
  "argdown": "argdown",
  "ad": "argdown",
  "mustache": "mustache",
  "stache": "mustache",
  "nim": "nim",
  "nims": "nim",
  "github-issues": "github",
  "ipynb": "notebook",
  "njk": "nunjucks",
  "nunjucks": "nunjucks",
  "nunjs": "nunjucks",
  "nunj": "nunjucks",
  "njs": "nunjucks",
  "nj": "nunjucks",
  "npm-debug.log": "npm",
  "npmignore": "npm_1",
  "npmrc": "npm_1",
  "ml": "ocaml",
  "mli": "ocaml",
  "cmx": "ocaml",
  "cmxa": "ocaml",
  "odata": "odata",
  "php.inc": "php",
  "pipeline": "pipeline",
  "pddl": "pddl",
  "plan": "plan",
  "happenings": "happenings",
  "prisma": "prisma",
  "pp": "puppet",
  "epp": "puppet",
  "purs": "purescript",
  "spec.jsx": "react_1",
  "test.jsx": "react_1",
  "cjsx": "react",
  "spec.tsx": "react_1",
  "test.tsx": "react_1",
  "re": "reasonml",
  "res": "rescript",
  "resi": "rescript_1",
  "r": "R",
  "rmd": "R",
  "erb": "html_erb",
  "erb.html": "html_erb",
  "html.erb": "html_erb",
  "sass": "sass",
  "springbeans": "spring",
  "slim": "slim",
  "smarty.tpl": "smarty",
  "tpl": "smarty",
  "sbt": "sbt",
  "scala": "scala",
  "sol": "ethereum",
  "styl": "stylus",
  "svelte": "svelte",
  "soql": "db_1",
  "tf": "terraform",
  "tf.json": "terraform",
  "tfvars": "terraform",
  "tfvars.json": "terraform",
  "dtx": "tex_2",
  "ins": "tex_3",
  "toml": "config",
  "twig": "twig",
  "spec.ts": "typescript_1",
  "test.ts": "typescript_1",
  "vala": "vala",
  "vapi": "vala",
  "component": "html_3",
  "vue": "vue",
  "wasm": "wasm",
  "wat": "wat",
  "pro": "prolog",
  "zig": "zig",
  "jar": "zip",
  "zip": "zip_1",
  "wgt": "wgt",
  "ai": "illustrator",
  "psd": "photoshop",
  "pdf": "pdf",
  "eot": "font",
  "ttf": "font",
  "woff": "font",
  "woff2": "font",
  "otf": "font",
  "avif": "image",
  "gif": "image",
  "jpg": "image",
  "jpeg": "image",
  "png": "image",
  "pxm": "image",
  "svg": "svg",
  "svgx": "image",
  "tiff": "image",
  "webp": "image",
  "sublime-project": "sublime",
  "sublime-workspace": "sublime",
  "mov": "video",
  "ogv": "video",
  "webm": "video",
  "avi": "video",
  "mpg": "video",
  "mp4": "video",
  "mp3": "audio",
  "ogg": "audio",
  "wav": "audio",
  "flac": "audio",
  "3ds": "svg_1",
  "3dm": "svg_1",
  "stl": "svg_1",
  "obj": "svg_1",
  "dae": "svg_1",
  "babelrc": "babel",
  "babelrc.js": "babel",
  "babelrc.cjs": "babel",
  "bazelrc": "bazel_1",
  "bowerrc": "bower",
  "dockerignore": "docker_1",
  "codeclimate.yml": "code-climate",
  "eslintrc": "eslint",
  "eslintrc.js": "eslint",
  "eslintrc.cjs": "eslint",
  "eslintrc.yaml": "eslint",
  "eslintrc.yml": "eslint",
  "eslintrc.json": "eslint",
  "eslintignore": "eslint_1",
  "firebaserc": "firebase",
  "gitlab-ci.yml": "gitlab",
  "jshintrc": "javascript_2",
  "jscsrc": "javascript_2",
  "stylelintrc": "stylelint",
  "stylelintrc.json": "stylelint",
  "stylelintrc.yaml": "stylelint",
  "stylelintrc.yml": "stylelint",
  "stylelintrc.js": "stylelint",
  "stylelintignore": "stylelint_1",
  "direnv": "config",
  "env": "config",
  "static": "config",
  "slugignore": "config",
  "tmp": "clock_1",
  "htaccess": "config",
  "key": "lock",
  "cert": "lock",
  "cer": "lock",
  "crt": "lock",
  "pem": "lock",
  "ds_store": "ignored"
};

export const SETI_FILE_NAMES: Record<string, string> = {
  "mix": "hex",
  "karma.conf.js": "karma",
  "karma.conf.cjs": "karma",
  "karma.conf.mjs": "karma",
  "karma.conf.coffee": "karma",
  "readme.md": "info",
  "readme.txt": "info",
  "readme": "info",
  "changelog.md": "clock",
  "changelog.txt": "clock",
  "changelog": "clock",
  "changes.md": "clock",
  "changes.txt": "clock",
  "changes": "clock",
  "version.md": "clock",
  "version.txt": "clock",
  "version": "clock",
  "mvnw": "maven",
  "pom.xml": "maven",
  "tsconfig.json": "tsconfig",
  "vite.config.js": "vite",
  "vite.config.ts": "vite",
  "vite.config.mjs": "vite",
  "vite.config.mts": "vite",
  "vite.config.cjs": "vite",
  "vite.config.cts": "vite",
  "swagger.json": "json_1",
  "swagger.yml": "json_1",
  "swagger.yaml": "json_1",
  "mime.types": "config",
  "jenkinsfile": "jenkins",
  "babel.config.js": "babel",
  "babel.config.json": "babel",
  "babel.config.cjs": "babel",
  "build": "bazel",
  "build.bazel": "bazel",
  "workspace": "bazel",
  "workspace.bazel": "bazel",
  "bower.json": "bower",
  "docker-healthcheck": "docker_2",
  "eslint.config.js": "eslint",
  "firebase.json": "firebase",
  "geckodriver": "firefox",
  "gruntfile.js": "grunt",
  "gruntfile.babel.js": "grunt",
  "gruntfile.coffee": "grunt",
  "gulpfile": "gulp",
  "gulpfile.js": "gulp",
  "ionic.config.json": "ionic",
  "ionic.project": "ionic",
  "platformio.ini": "platformio",
  "rollup.config.js": "rollup",
  "sass-lint.yml": "sass",
  "stylelint.config.js": "stylelint",
  "stylelint.config.cjs": "stylelint",
  "stylelint.config.mjs": "stylelint",
  "yarn.clean": "yarn",
  "yarn.lock": "yarn",
  "webpack.config.js": "webpack",
  "webpack.config.cjs": "webpack",
  "webpack.config.mjs": "webpack",
  "webpack.config.ts": "webpack",
  "webpack.config.build.js": "webpack",
  "webpack.config.build.cjs": "webpack",
  "webpack.config.build.mjs": "webpack",
  "webpack.config.build.ts": "webpack",
  "webpack.common.js": "webpack",
  "webpack.common.cjs": "webpack",
  "webpack.common.mjs": "webpack",
  "webpack.common.ts": "webpack",
  "webpack.dev.js": "webpack",
  "webpack.dev.cjs": "webpack",
  "webpack.dev.mjs": "webpack",
  "webpack.dev.ts": "webpack",
  "webpack.prod.js": "webpack",
  "webpack.prod.cjs": "webpack",
  "webpack.prod.mjs": "webpack",
  "webpack.prod.ts": "webpack",
  "license": "license",
  "licence": "license",
  "license.txt": "license",
  "licence.txt": "license",
  "license.md": "license",
  "licence.md": "license",
  "copying": "license",
  "copying.txt": "license",
  "copying.md": "license",
  "compiling": "license_1",
  "compiling.txt": "license_1",
  "compiling.md": "license_1",
  "contributing": "license_2",
  "contributing.txt": "license_2",
  "contributing.md": "license_2",
  "qmakefile": "makefile_1",
  "omakefile": "makefile_2",
  "cmakelists.txt": "makefile_3",
  "procfile": "heroku",
  "todo": "todo",
  "todo.txt": "todo",
  "todo.md": "todo",
  "npm-debug.log": "npm_ignored"
};

export const SETI_LANGUAGE_IDS: Record<string, string> = {
  "bat": "windows",
  "clojure": "clojure",
  "coffeescript": "coffee",
  "jsonc": "json",
  "json": "json",
  "c": "c",
  "cpp": "cpp",
  "cuda-cpp": "cu",
  "csharp": "c-sharp",
  "css": "css",
  "dart": "dart",
  "dockerfile": "docker",
  "ignore": "git",
  "fsharp": "f-sharp",
  "git-commit": "git",
  "go": "go2",
  "groovy": "grails",
  "handlebars": "mustache",
  "html": "html_3",
  "properties": "config",
  "java": "java",
  "javascriptreact": "react",
  "javascript": "javascript",
  "julia": "julia",
  "tex": "tex_1",
  "latex": "tex",
  "less": "less",
  "lua": "lua",
  "makefile": "makefile",
  "markdown": "markdown",
  "objective-c": "c_2",
  "objective-cpp": "cpp_2",
  "perl": "perl",
  "php": "php",
  "powershell": "powershell",
  "jade": "pug",
  "python": "python",
  "r": "R",
  "razor": "html",
  "ruby": "ruby",
  "rust": "rust",
  "scss": "sass",
  "search-result": "code-search",
  "shellscript": "shell",
  "sql": "db",
  "swift": "swift",
  "typescript": "typescript",
  "typescriptreact": "react",
  "xml": "xml",
  "dockercompose": "docker_3",
  "yaml": "yml",
  "argdown": "argdown",
  "bicep": "bicep",
  "elixir": "elixir",
  "elm": "elm",
  "erb": "html_erb",
  "github-issues": "github",
  "gradle": "gradle",
  "godot": "godot",
  "haml": "haml",
  "haskell": "haskell",
  "haxe": "haxe",
  "jinja": "jinja",
  "kotlin": "kotlin",
  "mustache": "mustache",
  "nunjucks": "nunjucks",
  "ocaml": "ocaml",
  "rescript": "rescript",
  "sass": "sass",
  "stylus": "stylus",
  "terraform": "terraform",
  "todo": "todo",
  "vala": "vala",
  "vue": "vue",
  "jsonl": "json",
  "postcss": "css",
  "django-html": "html_3",
  "blade": "php",
  "cursor-ai": "cursor"
};

export const SETI_DEFAULT_ICON = 'default';
