-- agentsam_project_context snapshot: inventory of agentsam_* D1 tables + where the repo uses them.
-- Idempotent: INSERT OR REPLACE by fixed id.
-- Apply prod:
--   ./scripts/with-cloudflare-env.sh npx wrangler d1 execute inneranimalmedia-business --remote -c wrangler.production.toml --file=./sql/agentsam/seed_agentsam_tables_inventory_project_context.sql

INSERT OR REPLACE INTO agentsam_project_context (
  id,
  tenant_id,
  workspace_id,
  project_key,
  project_name,
  project_type,
  status,
  priority,
  description,
  goals,
  constraints,
  current_blockers,
  primary_tables,
  secondary_tables,
  workers_involved,
  r2_buckets_involved,
  domains_involved,
  mcp_services_involved,
  key_files,
  related_routes,
  tokens_budgeted,
  tokens_used,
  cost_usd,
  linked_plan_id,
  linked_todo_ids,
  agent_id,
  client_id,
  session_id,
  created_by,
  notes,
  started_at,
  target_completion,
  completed_at,
  created_at,
  updated_at
)
SELECT
  'ctx_agentsam_tables_inventory',
  w.tenant_id,
  w.id,
  'agentsam_schema_inventory',
  'Agent Sam — agentsam_* table inventory & usage map',
  'platform_docs',
  'active',
  90,
  'Living snapshot of D1 agentsam_* tables documented from docs/db/agentsam-d1-context/2026-05-07_agentsam-schema.json plus migrations/code references. Use primary_tables for the export baseline; secondary_tables for tables wired in src/migrations but absent from that JSON export.',
  json_array(
    'Keep project_context as the human-facing map for which tables exist and typical call sites',
    'Regenerate or patch this row when major migrations add agentsam_* tables',
    'Prefer pragma/sqlite_master on prod for authoritative list vs this snapshot'
  ),
  json_array(
    'Do not treat this row as automated schema drift detection',
    'Tenant/workspace come from agentsam_workspace row ws_inneranimalmedia only for seed consistency'
  ),
  json_array(
    'Export JSON may lag behind production migrations',
    'Some tables exist only after applying numbered migrations (workflows graph, routing engine)'
  ),
  json_array(
    'agentsam_agent_run',
    'agentsam_ai',
    'agentsam_analytics',
    'agentsam_approval_queue',
    'agentsam_artifacts',
    'agentsam_bootstrap',
    'agentsam_browser_trusted_origin',
    'agentsam_cad_jobs',
    'agentsam_code_index_job',
    'agentsam_command_allowlist',
    'agentsam_command_pattern',
    'agentsam_command_run',
    'agentsam_commands',
    'agentsam_compaction_events',
    'agentsam_cron_runs',
    'agentsam_deployment_health',
    'agentsam_error_log',
    'agentsam_escalation',
    'agentsam_eval_cases',
    'agentsam_eval_runs',
    'agentsam_eval_suites',
    'agentsam_execution_context',
    'agentsam_executions',
    'agentsam_feature_flag',
    'agentsam_fetch_domain_allowlist',
    'agentsam_guardrail_events',
    'agentsam_guardrail_rulesets',
    'agentsam_guardrails',
    'agentsam_health_daily',
    'agentsam_hook',
    'agentsam_hook_execution',
    'agentsam_ignore_pattern',
    'agentsam_mcp_allowlist',
    'agentsam_mcp_servers',
    'agentsam_mcp_tool_execution',
    'agentsam_mcp_tools',
    'agentsam_mcp_workflows',
    'agentsam_memory',
    'agentsam_model_drift_signals',
    'agentsam_model_tier',
    'agentsam_plan_tasks',
    'agentsam_plans',
    'agentsam_project_context',
    'agentsam_prompt_cache_keys',
    'agentsam_prompt_versions',
    'agentsam_routing_arms',
    'agentsam_rules_document',
    'agentsam_script_runs',
    'agentsam_scripts',
    'agentsam_skill',
    'agentsam_skill_invocation',
    'agentsam_skill_revision',
    'agentsam_subagent_profile',
    'agentsam_subscription_registry',
    'agentsam_task_slos',
    'agentsam_todo',
    'agentsam_tool_call_log',
    'agentsam_tool_chain',
    'agentsam_tool_stats_compacted',
    'agentsam_tools',
    'agentsam_usage_events',
    'agentsam_usage_rollups_daily',
    'agentsam_user_feature_override',
    'agentsam_user_policy',
    'agentsam_webhook_events',
    'agentsam_webhook_weekly',
    'agentsam_workflow_runs',
    'agentsam_workspace',
    'agentsam_workspace_state'
  ),
  json_array(
    'agentsam_workflows',
    'agentsam_workflow_nodes',
    'agentsam_workflow_edges',
    'agentsam_execution_steps',
    'agentsam_model_catalog',
    'agentsam_route_requirements',
    'agentsam_model_routing_memory',
    'agentsam_execution_dependency_graph',
    'agentsam_execution_performance_metrics',
    'agentsam_rules_revision'
  ),
  json_array(
    'Cloudflare Worker (src/index.js → src/api/*.js, src/core/*.js)',
    'Optional: wrangler d1 execute for migrations'
  ),
  json_array(
    'agent-sam',
    'inneranimalmedia-assets',
    'iam-docs'
  ),
  json_array(
    'inneranimalmedia.com',
    'api.inneranimalmedia.com',
    'assets.inneranimalmedia.com',
    'tools.inneranimalmedia.com'
  ),
  json_array(
    'Remote MCP worker (env.MCP_SERVICE_URL)',
    'Hyperdrive → Supabase for mirrored observability'
  ),
  json_array(
    'docs/db/agentsam-d1-context/2026-05-07_agentsam-schema.json',
    'docs/db/agentsam-d1-context/2026-05-07_agentsam-schema-create-tables.sql',
    'migrations/286_agentsam_workflow_cms_theme_pipeline.sql',
    'migrations/291_agentsam_routing_engine_tables.sql',
    'migrations/314_agentsam_mcp_workflow_graph_mode_normalize.sql',
    'src/api/agent.js',
    'src/api/mcp.js',
    'src/api/analytics/overview.js',
    'src/core/workflow-executor.js',
    'src/core/workflows.js',
    'src/api/command-run-telemetry.js',
    'dashboard/components/McpPage.tsx',
    'dashboard/App.tsx'
  ),
  json_array(
    '/api/agent/boot',
    '/api/agent/sessions',
    '/api/agent/chat',
    '/api/mcp/agents',
    '/api/mcp/agent/:slug/chat',
    '/api/mcp/agent/:slug/workflows',
    '/api/mcp/tools',
    '/api/analytics/overview',
    '/dashboard/agent',
    '/dashboard/mcp',
    '/dashboard/mcp/:agentSlug'
  ),
  NULL,
  0,
  0,
  NULL,
  '[]',
  NULL,
  NULL,
  NULL,
  'repo_seed_agentsam_inventory',
    'Primary list = tables present in 2026-05-07_agentsam-schema.json export. Secondary = referenced in codebase/migrations but often created after that export (workflow DAG, execution_steps, routing engine, dependency graph, performance metrics). agentsam_prompt was dropped in migration 229 (unified registry). Reconcile with: SELECT name FROM sqlite_master WHERE type=''table'' AND name LIKE ''agentsam_%'' ORDER BY 1;',
  unixepoch(),
  NULL,
  NULL,
  unixepoch(),
  unixepoch()
FROM agentsam_workspace w
WHERE w.id = 'ws_inneranimalmedia';
